{
 "title": "IUF Timing Dashboard",
 "tags": [ "IUF" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Product",
    "label": "Product",
    "query": {
     "query": "label_values(argo_workflows_operation_counter, pname)"
    }
   },
   {
    "name": "Stage",
    "label": "Stage",
    "query": {
     "query": "label_values(argo_workflows_operation_counter{pname=~\"$Product\"}, stage)"
    }
   },
   {
    "name": "Operation",
    "label": "Operation",
    "query": {
     "query": "label_values(argo_workflows_operation_counter{pname=~\"$Product\", stage=~\"$Stage\"}, opname)"
    }
   },
   {
    "name": "FailedProducts",
    "label": "Failed Products",
    "query": {
     "query": "label_values(argo_workflows_operation_counter{pname=~\"$Product\", status=\"Failed\"}, pname)"
    }
   },
   {
    "name": "FailedStages",
    "label": "Failed Stages",
    "query": {
     "query": "label_values(argo_workflows_operation_counter{pname=~\"$Product\", stage=~\"$Stage\", status=~\"Failed\"}, stage)"
    }
   },
   {
    "name": "FailedOperations",
    "label": "Failed Operations",
    "query": {
     "query": "label_values(argo_workflows_operation_counter{pname=~\"$Product\", stage=~\"$Stage\", opname=~\"$Operation\", status=~\"Failed\"}, opname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Product details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total products",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "argo_workflows_operation_counter{pname=~\"$Product\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Product status",
   "type": "stat",
   "description": "The overall product status",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "expr": "argo_workflows_operation_counter{pname=~\"$FailedProducts\", status=\"Failed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total products succeeded",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "argo_workflows_operation_counter{pname=~\"$Product\", pname!~\"$FailedProducts\", status=\"Succeeded\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total products failed",
   "type": "gauge",
   "description": "The number of products that ran the goss tests, Number of products that failed, and Number of products that passed.",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "argo_workflows_operation_counter{pname=~\"$Product\", pname=~\"$FailedProducts\", status=\"Failed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total execution time for product",
   "type": "stat",
   "description": "Time to execute the test for the product selected",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "argo_workflows_operation_counter{pname=~\"$Product\"}"
    }
   ]
  },
  {
   "title": "Products detail",
   "type": "table",
   "description": "List of products with it's status and execution test",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(argo_workflows_operation_counter{pname=~\"$Product\", pname=~\"$FailedProducts\", status=\"Failed\"}) by (status, pname)"
    },
    {
     "expr": "sum(argo_workflows_operation_counter{pname=~\"$Product\", pname!~\"$FailedProducts\", status=~\"Succeeded\"}) by (status, pname)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Stage details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Total stages",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "argo_workflows_operation_counter{pname=~\"$Product\",stage=~\"$Stage\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stage status",
   "type": "stat",
   "description": "The result for the suite selected",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "expr": "argo_workflows_operation_counter{pname=~\"$Product\", stage=~\"$Stage\", stage=~\"$FailedStages\", status=\"Failed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total stages succeeded",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "argo_workflows_operation_counter{pname=~\"$Product\", stage=~\"$Stage\", stage!~\"$FailedStages\", status=\"Succeeded\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total stages failed",
   "type": "gauge",
   "description": "The number of products that ran the goss tests, Number of products that failed, and Number of products that passed.",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "argo_workflows_operation_counter{pname=~\"$Product\", stage=~\"$Stage\" ,stage=~\"$FailedStages\", status=\"Failed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total execution time for stage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "argo_workflows_operation_counter{pname=~\"$Product\", stage=~\"$Stage\"}"
    }
   ]
  },
  {
   "title": "Stages detail",
   "type": "table",
   "description": "List of stages with it's status and execution test",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(argo_workflows_operation_counter{pname=~\"$Product\", stage=~\"$FailedStages\", status=\"Failed\"}) by (status, stage)"
    },
    {
     "expr": "sum(argo_workflows_operation_counter{pname=~\"$Product\", stage!~\"$FailedStages\", status=~\"Succeeded\"}) by (status, stage)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Operation details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Total operations",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "argo_workflows_operation_counter{pname=~\"$Product\", stage=~\"$Stage\", opname=~\"$Operation\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operation status",
   "type": "stat",
   "description": "The result for the test selected",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "expr": "argo_workflows_operation_counter{pname=~\"$Product\", stage=~\"$Stage\", opname=~\"$Operation\", opname=~\"$FailedOperations\", status=~\"Failed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total operations succeeded",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "argo_workflows_operation_counter{pname=~\"$Product\", stage=~\"$Stage\", opname=~\"$Operation\", opname!~\"$FailedOperations\", status=\"Succeeded\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total operations failed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "argo_workflows_operation_counter{pname=~\"$Product\", stage=~\"$Stage\", opname=~\"$Operation\", opname=~\"$FailedOperations\", status=\"Failed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total execution time for operation",
   "type": "stat",
   "description": "Time to execute the selected test",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "argo_workflows_operation_counter{pname=~\"$Product\", stage=~\"$Stage\", opname=~\"$Operation\"}"
    }
   ]
  },
  {
   "title": "Operation detail",
   "type": "table",
   "description": "List of Operation with it's status and execution test",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(argo_workflows_operation_counter{pname=~\"$Product\", opname=~\"$FailedOperations\", status=\"Failed\"}) by (status, opname)"
    },
    {
     "expr": "sum(argo_workflows_operation_counter{pname=~\"$Product\", opname!~\"$FailedOperations\", status=~\"Succeeded\"}) by (status, opname)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Graph showing duration for each stage & operation",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "argo_workflows_operation_time{pdname=~\"$Product\", stage=~\"$Stage\", opname=~\"$Operation\"}"
    }
   ]
  }
 ]
}