{{/*
MIT License

(C) Copyright [2022] Hewlett Packard Enterprise Development LP

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "%s-%s" (include "cray-sysmgmt-health.fullname" .) "disk-space.rules" | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "cray-sysmgmt-health.name" . }}
{{ include "cray-sysmgmt-health.labels" . | indent 4 }}
{{- if (index .Values "customRules" "labels") }}
{{ toYaml (index .Values "customRules" "labels") | indent 4 }}
{{- end }}
{{- if (index .Values "customRules" "annotations") }}
  annotations:
{{ toYaml (index .Values "customRules" "annotations") | indent 4 }}
{{- end }}
spec:
  groups:
  - name: volume-status
    rules:
    - alert: RootVolumeFull
      annotations:
        message: ' Available space on mountpoint / is less than "{{`{{ $value | printf "%.2f" }}`}}" % '
      expr: node_filesystem_avail_bytes{mountpoint="/",job="node-exporter"} / node_filesystem_size_bytes{mountpoint="/",job="node-exporter"} < 0.05
      for: 1h
      labels:
        severity: critical
    - alert: ContainerdVolumeFull
      annotations:
        message: ' Available space on mountpoint /var/lib/containerd is less than "{{`{{ $value | printf "%.2f" }}`}}" % '
      expr: node_filesystem_avail_bytes{mountpoint="/var/lib/containerd",job="node-exporter"} / node_filesystem_size_bytes{mountpoint="/var/lib/containerd",job="node-exporter"} < 0.05
      for: 1h
      labels:
        severity: critical
    - alert: ContainersVolumeFull
      annotations:
        message: 'Available space on mountpoint /rootfs/var/lib/containers is less than "{{`{{ $value | printf "%.2f" }}`}}" % '
      expr: node_filesystem_avail_bytes{mountpoint="/rootfs/var/lib/containers",job="cray-sysmgmt-health-ceph-node-exporter"} / node_filesystem_size_bytes{mountpoint="/rootfs/var/lib/containers",job="cray-sysmgmt-health-ceph-node-exporter"} < 0.05
      for: 1h
      labels:
        severity: critical
    - alert: KubeletVolumeFull
      annotations:
        message: 'Available space on mountpoint /var/lib/kubelet is less than "{{`{{ $value | printf "%.2f" }}`}}" % '
      expr: node_filesystem_avail_bytes{mountpoint="/var/lib/kubelet",job="node-exporter"} / node_filesystem_size_bytes{mountpoint="/var/lib/kubelet",job="node-exporter"} < 0.05
      for: 1h
      labels:
        severity: critical
    - alert: CephVolumeFull
      annotations:
        message: 'Available space on mountpoint /rootfs/var/lib/ceph is less than "{{`{{ $value | printf "%.2f" }}`}}" % '
      expr: node_filesystem_avail_bytes{mountpoint="/rootfs/var/lib/ceph",job="cray-sysmgmt-health-ceph-node-exporter"} / node_filesystem_size_bytes{mountpoint="/rootfs/var/lib/ceph",job="cray-sysmgmt-health-ceph-node-exporter"} < 0.05
      for: 1h
      labels:
        severity: critical
    - alert: DiskWillFillIn30Mins
      annotations:
        message: ' Host disk will fill in less than 30 min (instance "{{`{{ $labels.instance }}`}}") '
      expr: predict_linear(node_filesystem_free_bytes{job="node-exporter"}[5m], 60 * 30) < 0 and on(instance) up{job="node-exporter"}
      for: 15m
      labels:
        severity: critical
    - alert: PodCpuUsageWarning
      expr: (sum(rate(container_cpu_usage_seconds_total{name!=""}[3m])) BY (instance, namespace, pod) * 100) > 70
      for: 2m
      labels:
        severity: warning
      annotations:
        message: ' Pod CPU usage is above 70% (instance "{{`{{ $labels.instance }}`}}") '
    - alert: PodCpuUsageTooHigh
      expr: (sum(rate(container_cpu_usage_seconds_total{name!=""}[3m])) BY (instance, namespace, pod) * 100) > 85
      for: 2m
      labels:
        severity: critical
      annotations:
        message: ' Pod CPU usage is above 85% (instance "{{`{{ $labels.instance }}`}}") '
    - alert: PodMemoryUsageWarning
      expr: (sum(container_memory_working_set_bytes{name!=""}) BY (instance, namespace, pod) / sum(container_spec_memory_limit_bytes > 0) BY (instance, namespace, pod) * 100)  > 70
      for: 2m
      labels:
        severity: warning
      annotations:
        message: ' Pod memory usage is above 70% (instance "{{`{{ $labels.instance }}`}}") '
    - alert: PodMemoryUsageTooHigh
      expr: (sum(container_memory_working_set_bytes{name!=""}) BY (instance, namespace, pod) / sum(container_spec_memory_limit_bytes > 0) BY (instance, namespace, pod) * 100)  > 85
      for: 2m
      labels:
        severity: critical
      annotations:
        message: ' Pod memory usage is above 85% (instance "{{`{{ $labels.instance }}`}}") '

