#
# MIT License
#
# (C) Copyright 2022-2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cray-sysmgmt-health.fullname" . }}-canu-test
  namespace: {{ .Release.Namespace }}
data:
  config.yml: |-
    global:
      config_version: 3
    input:
      type: file
      paths:
      - /logs/canu.log
      fail_on_missing_logfile: false
    grok_patterns:
      - 'NUM [0-9].*'
      - 'SWITCH [A-Za-z0-9-]+'
      - 'NAME ([A-Za-z0-9-()]+( [A-Za-z0-9-()]+)+)'
      - 'STATUS PASS|failed|FAIL|Failed|Fail'
    metrics:
      - type: gauge
        name: canu_test
        help: canu test result
        match: '.* %{NUM:num} \| %{SWITCH:sw} +\| %{NAME:nm} +\|.*%{STATUS:status}.*'
        value: '{{`{{if eq .status "PASS"}}1{{else}}0{{end}}`}}'
        labels:
          switch: '{{`{{.sw}}`}}'
          name: '{{`{{.nm}}`}}'
          status: '{{`{{.status}}`}}'
    server:
      port: 9144
