#
# MIT License
#
# (C) Copyright 2022-2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cray-sysmgmt-health.fullname" . }}-canu-test
  labels:
    app: canu-test
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canu-test
      sidecar: grok
  template:
    metadata:
      labels:
        app: canu-test
        sidecar: grok
    spec:
      containers:
        - name: canu-test
          image: {{ .Values.canuTest.image.repository }}:{{ .Values.canuTest.image.tag }}
          imagePullPolicy: {{ .Values.canuTest.image.pullPolicy }}
          env:
          - name: CRAYENV
            value: "k8s"
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ template "cray-sysmgmt-health.fullname" . }}-canu-test-secrets
                key: USERNAME
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "cray-sysmgmt-health.fullname" . }}-canu-test-secrets
                key: PASSWORD
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: logs
              mountPath: /logs/
        - name: grok
          image: {{ .Values.grokExporter.image.repository }}:{{ .Values.grokExporter.image.tag }}
          imagePullPolicy: {{ .Values.grokExporter.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9144
              protocol: TCP
          volumeMounts:
            - name: grok-config-volume
              mountPath: /etc/grok_exporter
            - name: logs
              mountPath: /logs
      volumes:
        - name: grok-config-volume
          configMap:
            name: {{ template "cray-sysmgmt-health.fullname" . }}-canu-test
        - name: logs
          emptyDir: {}
