{{- if (index .Values "prometheus-operator" "alertmanager" "enabled") }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "cray-sysmgmt-health.fullname" . }}-alertmanager
  labels:
    app: {{ template "cray-sysmgmt-health.name" . }}-alertmanager
{{ include "cray-sysmgmt-health.labels" . | indent 4 }}
spec:
  gateways:
  - {{ .Values.global.authGateway }}
  hosts:
  - {{ (index .Values "prometheus-operator" "alertmanager" "alertmanagerSpec" "externalAuthority") }}
  http:
  - match:
    - authority:
        exact: {{ (index .Values "prometheus-operator" "alertmanager" "alertmanagerSpec" "externalAuthority") }}
    route:
    - destination:
        host: {{ template "cray-sysmgmt-health.prometheus-operator.fullname" . }}-alertmanager
        port:
          number: 9093
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ template "cray-sysmgmt-health.fullname" . }}-alertmanager
  labels:
    app: {{ template "cray-sysmgmt-health.name" . }}-alertmanager
{{ include "cray-sysmgmt-health.labels" . | indent 4 }}
spec:
  host: {{ template "cray-sysmgmt-health.prometheus-operator.fullname" . }}-alertmanager
  trafficPolicy:
    tls:
      mode: DISABLE
{{- end }}
