#
# MIT License
#
# (C) Copyright 2021-2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
{{- /*
Copyright 2020 Hewlett Packard Enterprise Development LP
*/ -}}
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: {{ template "cray-sysmgmt-health.fullname" . }}-spire-postgres-exporter
  namespace: {{ .Values.spirePostgresExporter.serviceMonitor.namespace }}
  labels:
    app: {{ template "cray-sysmgmt-health.name" . }}-spire-postgres-exporter
    release: {{ template "cray-sysmgmt-health.name" . }}
{{ include "cray-sysmgmt-health.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      service: {{ template "cray-sysmgmt-health.name" . }}-spire-postgres-exporter
  namespaceSelector:
    matchNames:
      {{- range .Values.spirePostgresExporter.serviceMonitor.matchNamespace }}
      - {{ . }}
      {{- end }}
  endpoints:
  - port: {{ .Values.spirePostgresExporter.serviceMonitor.port }}
    {{- if .Values.spirePostgresExporter.serviceMonitor.interval }}
    interval: {{ .Values.spirePostgresExporter.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.spirePostgresExporter.serviceMonitor.scheme }}
    scheme: {{ .Values.spirePostgresExporter.serviceMonitor.scheme }}
    {{- end }}
{{- if .Values.spirePostgresExporter.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.spirePostgresExporter.serviceMonitor.metricRelabelings | indent 4) . }}
{{- end }}
{{- if .Values.spirePostgresExporter.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.spirePostgresExporter.serviceMonitor.relabelings | indent 4 }}
{{- end }}
