{
 "title": "SMARTMON",
 "description": "Smartmon Texfile node_exporter Dashboard",
 "tags": [
  "prometheus",
  "node_exporter",
  "smartmon"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(smartmon_smartctl_version, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Unhealthy Disks",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "smartmon_device_smart_healthy{instance=~\"$instance\"} < 1"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(smartmon_airflow_temperature_cel_value{instance=~\"$instance\"}) by (instance, disk)",
     "legendFormat": "val {{instance}} {{disk}}"
    },
    {
     "expr": "avg(smartmon_airflow_temperature_cel_raw_value{instance=~\"$instance\"}) by (instance, disk)",
     "legendFormat": "raw {{instance}} {{disk}}"
    }
   ]
  },
  {
   "title": "Raw Error Read Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(smartmon_total_lbas_read_value{instance=~\"$instance\"}) by (instance, disk)",
     "legendFormat": "val {{instance}} {{disk}}"
    },
    {
     "expr": "avg(smartmon_spin_retry_count_raw_value{instance=~\"$instance\"}) by (instance, disk)",
     "legendFormat": "raw {{instance}} {{disk}}"
    }
   ]
  },
  {
   "title": "Raw Error Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(smartmon_total_lbas_written_value{instance=~\"$instance\"}) by (instance, disk)",
     "legendFormat": "val {{instance}} {{disk}}"
    },
    {
     "expr": "avg(smartmon_total_lbas_written_raw_value{instance=~\"$instance\"}) by (instance, disk)",
     "legendFormat": "raw {{instance}} {{disk}}"
    }
   ]
  },
  {
   "title": "Reallocated Sectors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "smartmon_reallocated_sector_ct_raw_value{instance=~\"$instance\"}",
     "legendFormat": "raw {{instance}} {{disk}}"
    },
    {
     "expr": "smartmon_reallocated_sector_ct_value{instance=~\"$instance\"}",
     "legendFormat": "val {{instance}} {{disk}}"
    }
   ]
  },
  {
   "title": "Current Pending Sectors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "smartmon_current_pending_sector_raw_value{instance=~\"$instance\"}",
     "legendFormat": "raw {{instance}} {{disk}}"
    },
    {
     "expr": "smartmon_current_pending_sector_value{instance=~\"$instance\"}",
     "legendFormat": "val {{instance}} {{disk}}"
    }
   ]
  }
 ]
}