#
# MIT License
#
# (C) Copyright 2021-2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
{{- if and (index .Values "customRules" "create") (index .Values "customRules" "rules" "etcd") }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: {{ printf "%s-%s" (include "cray-sysmgmt-health.fullname" .) "etcd" | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "cray-sysmgmt-health.name" . }}
{{ include "cray-sysmgmt-health.labels" . | indent 4 }}
{{- if (index .Values "customRules" "labels") }}
{{ toYaml (index .Values "customRules" "labels") | indent 4 }}
{{- end }}
{{- if (index .Values "customRules" "annotations") }}
  annotations:
{{ toYaml (index .Values "customRules" "annotations") | indent 4 }}
{{- end }}
spec:
  groups:
  - name: etcd
    rules:
    - alert: etcdInsufficientMembers
      annotations:
        description: 'etcd cluster "{{`{{ $labels.job }}`}}": insufficient members ({{`{{ $value }}`}}).'
      expr: sum(up{job=~".*etcd.*"} == bool 1) by (job) < ((count(up{job=~".*etcd.*"})
        by (job) + 1) / 2)
      for: 3m
      labels:
        severity: critical
        group: prometheus
    - alert: etcdNoLeader
      annotations:
        description: 'etcd cluster "{{`{{ $labels.job }}`}}": member {{`{{ $labels.instance }}`}} has no leader.'
      expr: etcd_server_has_leader{job=~".*etcd.*"} == 0
      for: 1m
      labels:
        severity: critical
        group: prometheus
    - alert: etcdHighNumberOfLeaderChanges
      annotations: 
        description: >
          etcd cluster "{{`{{ $labels.job }}`}}": instance "{{`{{ $labels.instance }}`}}"
          has seen "{{`{{ $value }}`}}" leader changes within the last hour.
      expr: rate(etcd_server_leader_changes_seen_total{job=~".*etcd.*"}[15m]) > 3
      for: 15m
      labels:
        severity: warning
        group: prometheus
    - alert: etcdGRPCRequestsSlow
      annotations: 
        description: >
          etcd cluster "{{`{{ $labels.job }}`}}": gRPC requests to "{{`{{ $labels.grpc_method }}`}}" 
          are taking "{{`{{ $value }}`}}"s on etcd instance "{{`{{ $labels.instance }}`}}".
      expr: |-
        histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{job=~".*etcd.*", grpc_type="unary"}[5m])) by (job, instance, grpc_service, grpc_method, le))
        > 0.15
      for: 10m
      labels:
        severity: critical
        group: prometheus
    - alert: etcdMemberCommunicationSlow
      annotations: 
        description: >
          etcd cluster "{{`{{ $labels.job }}`}}": member communication with "{{`{{ $labels.To }}`}}"
          is taking "{{`{{ $value }}`}}"s on etcd instance "{{`{{ $labels.instance }}`}}".
      expr: |-
        histogram_quantile(0.99, rate(etcd_network_peer_round_trip_time_seconds_bucket{job=~".*etcd.*"}[5m]))
        > 0.15
      for: 10m
      labels:
        severity: warning
        group: prometheus
    - alert: etcdHighNumberOfFailedProposals
      annotations: 
        description: >
          etcd cluster "{{`{{ $labels.job }}`}}": "{{`{{ $value }}`}}" proposal failures
          within the last hour on etcd instance "{{`{{ $labels.instance }}`}}".
      expr: rate(etcd_server_proposals_failed_total{job=~".*etcd.*"}[15m]) > 5
      for: 15m
      labels:
        severity: warning
        group: prometheus
    - alert: etcdHighFsyncDurations
      annotations: 
        description: >
          etcd cluster "{{`{{ $labels.job }}`}}": 99th percentile fync durations
          are "{{`{{ $value }}`}}"s on etcd instance "{{`{{ $labels.instance }}`}}".
      expr: |-
        histogram_quantile(0.99, rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=~".*etcd.*"}[5m]))
        > 0.5
      for: 10m
      labels:
        severity: warning
        group: prometheus
    - alert: etcdHighCommitDurations
      annotations:
        description: >
          etcd cluster "{{`{{ $labels.job }}`}}": 99th percentile commit durations
          "{{`{{ $value }}`}}"s on etcd instance "{{`{{ $labels.instance }}`}}".
      expr: |-
        histogram_quantile(0.99, rate(etcd_disk_backend_commit_duration_seconds_bucket{job=~".*etcd.*"}[5m]))
        > 0.25
      for: 10m
      labels:
        severity: warning
        group: prometheus
    - alert: etcdHighNumberOfFailedHTTPRequests
      annotations: 
        description: >
          "{{`{{ $value }}`}}% of requests for "{{`{{ $labels.method }}`}}" failed on etcd
          instance "{{`{{ $labels.instance }}`}}"
      expr: |-
        sum(rate(etcd_http_failed_total{job=~".*etcd.*", code!="404"}[5m])) BY (method) / sum(rate(etcd_http_received_total{job=~".*etcd.*"}[5m]))
        BY (method) > 0.01
      for: 10m
      labels:
        severity: warning
        group: prometheus
    - alert: etcdHighNumberOfFailedHTTPRequests
      annotations:
        description: >
          "{{`{{ $value }}`}}"% of requests for "{{`{{ $labels.method }}`}}" failed on etcd
          instance "{{`{{ $labels.instance }}`}}".
      expr: |-
        sum(rate(etcd_http_failed_total{job=~".*etcd.*", code!="404"}[5m])) BY (method) / sum(rate(etcd_http_received_total{job=~".*etcd.*"}[5m]))
        BY (method) > 0.05
      for: 10m
      labels:
        severity: critical
        group: prometheus
    - alert: etcdHTTPRequestsSlow
      annotations:
        description: etcd instance "{{`{{ $labels.instance }}`}}" HTTP requests to "{{`{{ $labels.method }}`}}" are slow.
      expr: |-
        histogram_quantile(0.99, rate(etcd_http_successful_duration_seconds_bucket[5m]))
        > 0.15
      for: 10m
      labels:
        severity: warning
        group: prometheus
{{- end }}
