{
 "title": "Critical Services Monitoring Dashboard",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{reporter=\"destination\",destination_workload=~\"cray-smd\",destination_service=~\"cray-smd.services.svc.cluster.local\"}[1m])), 0.001)",
     "legendFormat": "cray-smd"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{reporter=\"destination\",destination_workload=~\"cray-hbtd\",destination_service=~\"cray-hbtd.services.svc.cluster.local\"}[1m])), 0.001)",
     "legendFormat": "cray-hbtd"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{reporter=\"destination\",destination_workload=~\"cray-capmc\",destination_service=~\"cray-capmc.services.svc.cluster.local\"}[1m])), 0.001)",
     "legendFormat": "cray-capmc"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{reporter=\"destination\",destination_workload=~\"cray-smd-postgres\",destination_service=~\"cray-smd-postgres.services.svc.cluster.local\"}[1m])), 0.001)",
     "legendFormat": "cray-smd-postgres"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{reporter=\"destination\",destination_workload=~\"cray-bss\",destination_service=~\"cray-bss.services.svc.cluster.local\"}[1m])), 0.001)",
     "legendFormat": "cray-bss"
    }
   ]
  },
  {
   "title": "P50 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"cray-smd\",destination_service=~\"cray-smd.services.svc.cluster.local\"}[1m])) by (destination_workload, destination_workload_namespac, le)) / 1000)",
     "legendFormat": "cray-smd"
    },
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"cray-hbtd\",destination_service=~\"cray-hbtd.services.svc.cluster.local\"}[1m])) by (destination_workload, destination_workload_namespac, le)) / 1000)",
     "legendFormat": "cray-hbtd"
    },
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"cray-capmc\",destination_service=~\"cray-capmc.services.svc.cluster.local\"}[1m])) by (destination_workload, destination_workload_namespac, le)) / 1000)",
     "legendFormat": "cray-capmc"
    },
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"cray-smd-postgres\",destination_service=~\"cray-smd-postgres.services.svc.cluster.local\"}[1m])) by (destination_workload, destination_workload_namespac, le)) / 1000)",
     "legendFormat": "cray-smd-postgres"
    },
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"cray-bss\",destination_service=~\"cray-bss.services.svc.cluster.local\"}[1m])) by (destination_workload, destination_workload_namespac, le)) / 1000)",
     "legendFormat": "cray-bss"
    }
   ]
  },
  {
   "title": "P99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"cray-smd\",destination_service=~\"cray-smd.services.svc.cluster.local\"}[1m])) by (destination_workload, destination_workload_namespac, le)) / 1000)",
     "legendFormat": "cray-smd"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"cray-hbtd\",destination_service=~\"cray-hbtd.services.svc.cluster.local\"}[1m])) by (destination_workload, destination_workload_namespac, le)) / 1000)",
     "legendFormat": "cray-hbtd"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"cray-capmc\",destination_service=~\"cray-capmc.services.svc.cluster.local\"}[1m])) by (destination_workload, destination_workload_namespac, le)) / 1000)",
     "legendFormat": "cray-capmc"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"cray-smd-postgres\",destination_service=~\"cray-smd-postgres.services.svc.cluster.local\"}[1m])) by (destination_workload, destination_workload_namespac, le)) / 1000)",
     "legendFormat": "cray-smd-postgres"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"cray-bss\",destination_service=~\"cray-bss.services.svc.cluster.local\"}[1m])) by (destination_workload, destination_workload_namespac, le)) / 1000)",
     "legendFormat": "cray-bss"
    }
   ]
  }
 ]
}