{
 "title": "Istio Performance Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Performance Dashboard Notes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Performance Dashboard README",
     "type": "text",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "The charts on this dashboard are intended to show Istio main components cost in terms resources utilization under steady load.\n\n- **vCPU/1k rps:** shows vCPU utilization by the main Istio components normalized by 1000 requests/second. When idle or low traffic, this chart will be blank. The curve for istio-proxy refers to the services sidecars only.\n- **vCPU:** vCPU utilization by Istio components, not normalized.\n- **Memory:** memory footprint for the components. Telemetry and policy are normalized by 1k rps, and no data is shown  when there is no traffic. For ingress and istio-proxy, the data is per instance.\n- **Bytes transferred/ sec:** shows the number of bytes flowing through each Istio component.\n\n\n"
     }
    }
   ]
  },
  {
   "title": "vCPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "vCPU / 1k rps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(irate(container_cpu_usage_seconds_total{job=\"kubelet\",pod=~\"istio-ingressgateway-.*\",container=\"istio-proxy\"}[1m])) / (round(sum(irate(istio_requests_total{source_workload=\"istio-ingressgateway\", reporter=\"destination\"}[1m])), 0.001)/1000))",
     "legendFormat": "istio-ingressgateway"
    },
    {
     "expr": "(sum(irate(container_cpu_usage_seconds_total{job=\"kubelet\",namespace!=\"istio-system\",container=\"istio-proxy\"}[1m]))/ (round(sum(irate(istio_requests_total[1m])), 0.001)/1000))/ (sum(irate(istio_requests_total{source_workload=\"istio-ingressgateway\"}[1m])))",
     "legendFormat": "istio-proxy"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\",pod=~\"istio-ingressgateway-.*\",container=\"istio-proxy\"}[1m]))",
     "legendFormat": "istio-ingressgateway"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\",namespace!=\"istio-system\",container=\"istio-proxy\"}[1m]))",
     "legendFormat": "istio-proxy"
    }
   ]
  },
  {
   "title": "Memory and Data Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{job=\"kubelet\",pod=~\"istio-ingressgateway-.*\"}) / count(container_memory_usage_bytes{job=\"kubelet\",pod=~\"istio-ingressgateway-.*\",container!=\"POD\"})",
     "legendFormat": "per istio-ingressgateway"
    },
    {
     "expr": "sum(container_memory_usage_bytes{job=\"kubelet\",namespace!=\"istio-system\",container=\"istio-proxy\"}) / count(container_memory_usage_bytes{job=\"kubelet\",namespace!=\"istio-system\",container=\"istio-proxy\"})",
     "legendFormat": "per istio proxy"
    }
   ]
  },
  {
   "title": "Bytes transferred / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(istio_response_bytes_sum{source_workload=\"istio-ingressgateway\", reporter=\"destination\"}[1m]))",
     "legendFormat": "istio-ingressgateway"
    },
    {
     "expr": "sum(irate(istio_response_bytes_sum{source_workload_namespace!=\"istio-system\", reporter=\"source\"}[1m])) + sum(irate(istio_response_bytes_sum{destination_workload_namespace!=\"istio-system\", reporter=\"destination\"}[1m])) + sum(irate(istio_request_bytes_sum{source_workload_namespace!=\"istio-system\", reporter=\"source\"}[1m])) + sum(irate(istio_request_bytes_sum{destination_workload_namespace!=\"istio-system\", reporter=\"destination\"}[1m]))",
     "legendFormat": "istio-proxy"
    }
   ]
  },
  {
   "title": "Istio Component Versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Istio Components by Version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(istio_build) by (component, tag)",
     "legendFormat": "{{ component }}: {{ tag }}"
    }
   ]
  },
  {
   "title": "Proxy Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{job=\"kubelet\",container=\"istio-proxy\"})",
     "legendFormat": "{{ container }} (k8s)"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\",container=\"istio-proxy\"}[1m]))",
     "legendFormat": "Total (k8s)"
    }
   ]
  },
  {
   "title": "DiskIO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_reads_bytes_total{job=\"kubelet\", container=\"istio-proxy\"})",
     "legendFormat": "total reads bytes"
    },
    {
     "expr": "sum(container_fs_writes_bytes_total{job=\"kubelet\", container=\"istio-proxy\"})",
     "legendFormat": "total writes bytes"
    }
   ]
  },
  {
   "title": "Pilot Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{istio=\"pilot\"}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "process_resident_memory_bytes{istio=\"pilot\"}",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "go_memstats_alloc_bytes{istio=\"pilot\"}",
     "legendFormat": "Alloc"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{istio=\"pilot\"}",
     "legendFormat": "Heap in-use"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{istio=\"pilot\"}",
     "legendFormat": "Stack in-use"
    },
    {
     "expr": "sum(container_memory_usage_bytes{job=\"kubelet\",container=~\"discovery|istio-proxy\", pod=~\"istiod-.*\"})",
     "legendFormat": "Total (k8s)"
    },
    {
     "expr": "container_memory_usage_bytes{job=\"kubelet\",container=~\"discovery|istio-proxy\", pod=~\"istiod-.*\"}",
     "legendFormat": "{{ container }} (k8s)"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\",container=~\"discovery|istio-proxy\", pod=~\"istiod-.*\"}[1m]))",
     "legendFormat": "Total (k8s)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\",container=~\"discovery|istio-proxy\", pod=~\"istiod-.*\"}[1m])) by (container)",
     "legendFormat": "{{ container }} (k8s)"
    },
    {
     "expr": "irate(process_cpu_seconds_total{istio=\"pilot\"}[1m])",
     "legendFormat": "pilot (self-reported)"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{istio=\"pilot\"}",
     "legendFormat": "Number of Goroutines"
    }
   ]
  }
 ]
}