{
 "title": "Microservice Health Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"dashboard-header text-center\">\n<span>AGGREGATED SERVICES HEALTH</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Client Request Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{reporter=\"source\"}[5m])), 0.001)"
    }
   ]
  },
  {
   "title": "(2xx responses)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\",response_code=~\"2.*\"}[5m])) / sum(irate(istio_requests_total{reporter=\"source\"}[5m]))"
    }
   ]
  },
  {
   "title": "(3xx responses)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\",response_code=~\"3.*\"}[5m])) / sum(irate(istio_requests_total{reporter=\"source\"}[5m]))"
    }
   ]
  },
  {
   "title": "(4xx responses)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\",response_code=~\"4.*\"}[5m])) / sum(irate(istio_requests_total{reporter=\"source\"}[5m]))"
    }
   ]
  },
  {
   "title": "Server Request Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{reporter=\"destination\"}[5m])), 0.001)"
    }
   ]
  },
  {
   "title": "(2xx responses)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\",response_code=~\"2.*\"}[5m])) / sum(irate(istio_requests_total{reporter=\"destination\"}[5m]))"
    }
   ]
  },
  {
   "title": "(3xx responses)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\",response_code=~\"3.*\"}[5m])) / sum(irate(istio_requests_total{reporter=\"destination\"}[5m]))"
    }
   ]
  },
  {
   "title": "(4xx responses)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\",response_code=~\"4.*\"}[5m])) / sum(irate(istio_requests_total{reporter=\"destination\"}[5m]))"
    }
   ]
  },
  {
   "title": "Client Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\"}[1m])) by (le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\"}[1m])) by (le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\"}[1m])) by (le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Server Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\"}[1m])) by (le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\"}[1m])) by (le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\"}[1m])) by (le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
   "options": {
    "content": "<div class=\"dashboard-header text-center\">\n<span>AGGREGATED CLIENT WORKLOADS</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Incoming Requests by Source And Response Code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\",reporter=\"source\"}[5m])) by (source_workload, source_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\"}[5m])) by (source_workload, source_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "Incoming Success Rate (non-5xx responses) By Source",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy=\"mutual_tls\",response_code!~\"5.*\"}[5m])) by (source_workload, source_workload_namespace) / sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy=\"mutual_tls\"}[5m])) by (source_workload, source_workload_namespace)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\", response_code!~\"5.*\"}[5m])) by (source_workload, source_workload_namespace) / sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy!=\"mutual_tls\"}[5m])) by (source_workload, source_workload_namespace)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }}"
    }
   ]
  },
  {
   "title": "Incoming Request Duration by Source",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99"
    }
   ]
  },
  {
   "title": "Incoming Request Size By Source",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}}  P90 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}}  P99 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99"
    }
   ]
  },
  {
   "title": "Response Size By Source",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}}  P90 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}}  P99 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 },
   "options": {
    "content": "<div class=\"dashboard-header text-center\">\n<span>AGGREGATED SERVICE WORKLOADS</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Incoming Requests by Destination And Response Code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\",reporter=\"destination\"}[5m])) by (destination_workload, destination_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", reporter=\"destination\"}[5m])) by (destination_workload, destination_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "Incoming Success Rate (non-5xx responses) By Source",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\", connection_security_policy=\"mutual_tls\",response_code!~\"5.*\"}[5m])) by (destination_workload, destination_workload_namespace) / sum(irate(istio_requests_total{reporter=\"destination\", connection_security_policy=\"mutual_tls\"}[5m])) by (destination_workload, destination_workload_namespace)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\", connection_security_policy!=\"mutual_tls\",response_code!~\"5.*\"}[5m])) by (destination_workload, destination_workload_namespace) / sum(irate(istio_requests_total{reporter=\"destination\", connection_security_policy!=\"mutual_tls\"}[5m])) by (destination_workload, destination_workload_namespace)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
    }
   ]
  },
  {
   "title": "Incoming Request Duration by Source",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P90 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P99 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P90"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P99"
    }
   ]
  },
  {
   "title": "Incoming Request Size By Source",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}  P90 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}  P99 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P99"
    }
   ]
  },
  {
   "title": "Response Size By Source",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}  P90 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}  P99 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P99"
    }
   ]
  }
 ]
}