{
 "title": "Logstash",
 "description": "Logstash Health Monitoring: System, JVM, Pipeline and individual plugin stats for Logstash replicas running on Kubernetes.",
 "tags": [
  "monitoring-services",
  "SIM"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cpu_threshold", "label": "CPU Threshold", "query": "1.0" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(logstash_info_node)"
    }
   },
   {
    "name": "pipeline",
    "label": "Logstash Pipeline",
    "query": {
     "query": "query_result(logstash_stats_pipeline_events_in{instance=~'$instance'})"
    }
   },
   {
    "name": "input_plugin",
    "query": {
     "query": "query_result(logstash_stats_pipeline_plugin_events_out{instance=~'$instance',plugin_type='input'})"
    }
   },
   {
    "name": "filter_plugin",
    "query": {
     "query": "query_result(logstash_stats_pipeline_plugin_events_out{instance=~'$instance',plugin_type='filter'})"
    }
   },
   {
    "name": "output_plugin",
    "query": {
     "query": "query_result(logstash_stats_pipeline_plugin_events_out{instance=~'$instance',plugin_type='output'})"
    }
   },
   {
    "name": "plugin_type",
    "label": "Plugin Type",
    "query": {
     "query": "query_result(logstash_stats_pipeline_plugin_events_duration{instance=~'$instance'})"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Deployed Chart Version by Instance",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(logstash_info_node)", "legendFormat": "logstash instances" },
    {
     "expr": "max (sum by (instance) (logstash_stats_pipeline_up))",
     "legendFormat": "Total number of Pipeline (per instance)"
    }
   ]
  },
  {
   "title": "Total Events In/Out",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(logstash_stats_pipeline_events_in{instance=~'$instance',pipeline=~'$pipeline'}[$__range]))",
     "legendFormat": "IN"
    },
    {
     "expr": "sum(increase(logstash_stats_pipeline_events_out{instance=~'$instance',pipeline=~'$pipeline'}[$__range]))",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "Status Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pipeline Status + Max Rate Last Hour",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(logstash_stats_pipeline_events_out{instance=~'$instance',pipeline=~\"$pipeline\"}[$__range]) / rate(logstash_stats_pipeline_events_duration{instance=~'$instance',pipeline=~\"$pipeline\"}[$__range])*1000 > 0) by (pipeline) or max(logstash_stats_pipeline_up{}) by (pipeline)",
     "legendFormat": "{{rate}}"
    }
   ]
  },
  {
   "title": "Output Write Successes Rate (%)",
   "type": "stat",
   "description": "Successful Writes to Elasticsearch/OpenSearch",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (pipeline) (logstash_stats_pipeline_plugin_documents_successes{plugin!=\"stdout\"}) / ((sum by (pipeline) (logstash_stats_pipeline_plugin_documents_successes{plugin!=\"stdout\"})) + (sum by (pipeline) (logstash_stats_pipeline_plugin_documents_non_retryable_failures{plugin!=\"stdout\"}))) *100) ",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "System Load Averages by Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System Load Average in 15m ($instance) ",
   "type": "timeseries",
   "description": "Processes using or waiting for CPU",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "repeat": "pod",
   "targets": [
    {
     "expr": "logstash_stats_process_cpu_load_average_15m{instance=~'$instance'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Load Average in 5m ($instance)",
   "type": "timeseries",
   "description": "Processes using or waiting for CPU",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "logstash_stats_process_cpu_load_average_5m{instance=~'$instance'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process Metrics (All Selected Instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "logstash_stats_process_cpu_percent{instance=~'$instance'}",
     "legendFormat": "cpu_pct ({{instance}})"
    }
   ]
  },
  {
   "title": "Logstash Process Total Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "logstash_stats_process_mem_total_virtual{instance=~'$instance'}",
     "legendFormat": "vmem ({{instance}})"
    }
   ]
  },
  {
   "title": "Logstash Open FIle Descriptors %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "logstash_stats_process_open_file_descriptors{instance=~'$instance'} / logstash_stats_process_max_file_descriptors{instance=~'$instance'} *100",
     "legendFormat": "percent_open_fds ({{instance}}) "
    }
   ]
  },
  {
   "title": "JVM  (All Selected Instances)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Heap % used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "logstash_stats_jvm_mem_heap_used_percent{instance=~'$instance'}",
     "legendFormat": "{{instance}}-jvm-usage"
    }
   ]
  },
  {
   "title": "JVM Heap usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "logstash_stats_jvm_mem_heap_used_bytes{instance=~'$instance'}",
     "legendFormat": "{{instance}}-jvm-used"
    },
    {
     "expr": "logstash_stats_jvm_mem_heap_max_bytes{instance=~'$instance'}",
     "legendFormat": "{{instance}}-jvm-max"
    }
   ]
  },
  {
   "title": "Threads count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "logstash_stats_jvm_threads_count{instance=~'$instance'}",
     "legendFormat": "{{instance}}-threads_count"
    },
    {
     "expr": "logstash_stats_jvm_threads_peak_count{instance=~'$instance'}",
     "legendFormat": "{{instance}}-threads_peak"
    }
   ]
  },
  {
   "title": "Young pool usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "logstash_stats_jvm_mem_pool_committed_bytes{pool='young',instance=~'$instance'}",
     "legendFormat": "young_pool_committed ({{instance}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_max_bytes{pool='young',instance=~'$instance'}",
     "legendFormat": "\"young_pool_max  ({{instance}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_max_bytes{pool='young',instance=~'$instance'}",
     "legendFormat": "young_pool_peak  ({{instance}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_used_bytes{pool='young',instance=~'$instance'}",
     "legendFormat": "young_pool_peak_used ({{instance}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_used_bytes{pool='young',instance=~'$instance'}",
     "legendFormat": "young_used ({{instance}})"
    }
   ]
  },
  {
   "title": "Survivor pool usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "logstash_stats_jvm_mem_pool_committed_bytes{pool='survivor',instance=~'$instance'}",
     "legendFormat": "{{instance}}-survivor_pool_committed"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_max_bytes{pool='survivor',instance=~'$instance'}",
     "legendFormat": "{{instance}}-survivor_pool_max"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_max_bytes{pool='survivor',instance=~'$instance'}",
     "legendFormat": "{{instance}}-survivor_pool_peak_max"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_used_bytes{pool='survivor',instance=~'$instance'}",
     "legendFormat": "{{instance}}-survivor_pool_peak_used"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_used_bytes{pool='survivor',instance=~'$instance'}",
     "legendFormat": "{{instance}}-survivor_used"
    }
   ]
  },
  {
   "title": "Old pool usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "logstash_stats_jvm_mem_pool_committed_bytes{pool='old',instance=~'$instance'}",
     "legendFormat": "old_pool_committed ({{instance}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_max_bytes{pool='old',instance=~'$instance'}",
     "legendFormat": "old_pool_max ({{instance}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_max_bytes{pool='old',instance=~'$instance'}",
     "legendFormat": "old_pool_peak_max ({{instance}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_used_bytes{pool='old',instance=~'$instance'}",
     "legendFormat": "old_pool_peak_used ({{instance}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_used_bytes{pool='old',instance=~'$instance'}",
     "legendFormat": "old_used ({{instance}})"
    }
   ]
  },
  {
   "title": "Pipeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$instance - Events processing times",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 74 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(irate(logstash_stats_pipeline_events_queue_push_duration{instance=~'$instance'}[$__range])/irate(logstash_stats_pipeline_events_in{instance=~'$instance'}[$__range])) by (instance, pipeline)",
     "legendFormat": "avg waiting time ({{pipeline}})"
    },
    {
     "expr": "avg(irate(logstash_stats_pipeline_events_duration{instance=~'$instance'}[$__range])/irate(logstash_stats_pipeline_events_out{instance=~'$instance'}[$__range])) by (instance, pipeline)",
     "legendFormat": "avg process time  ({{pipeline}})"
    }
   ]
  },
  {
   "title": "Pipeline Queue Size ($pipeline)",
   "type": "timeseries",
   "description": "Documents in Queue",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
   "repeat": "pod",
   "targets": [
    {
     "expr": "logstash_stats_pipeline_queue_events_count{instance=~'$instance',pipeline=~'$pipeline'}",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Pipeline Inputs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pipeline Input events / sec over the last hour ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 88 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job) (irate(logstash_stats_pipeline_events_in{instance=~'$instance'}[$__range]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Input plugins: Queue Push Waiting Times ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 95 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(increase(logstash_stats_pipeline_plugin_events_queue_push_duration{instance=~'$instance',pipeline=~\"$pipeline\",plugin=~'$input_plugin',plugin_type='input'}[$__range])*1000/increase(logstash_stats_pipeline_plugin_events_out{instance=~'$instance',pipeline=~\"$pipeline\",plugin=~'$input_plugin',plugin_type='input'}[$__range])) by (instance, pipeline, plugin)",
     "legendFormat": "queue wait: ({{pipeline}}::{{plugin}})"
    }
   ]
  },
  {
   "title": "Pipeline Outputs ($pipeline)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Output events ($instance) ($output_plugin)",
   "type": "timeseries",
   "description": "An \"output event\" is a 20MB \"bulk\" send in most cases",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 103 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(logstash_stats_pipeline_plugin_events_out{instance=~'$instance',pipeline=~\"$pipeline\",plugin=~'$output_plugin',plugin_type='output'}[$__range])",
     "legendFormat": "{{instance}} ({{pipeline}}) [{{plugin}}]"
    }
   ]
  },
  {
   "title": "Pipeline Output events / sec over the last hour ($instance)",
   "type": "timeseries",
   "description": "An \"output event\" is a 20MB \"bulk\" send in most cases",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 109 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job) (irate(logstash_stats_pipeline_plugin_events_out{instance=~'$instance',plugin_type='output'}[$__range]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Pipeline I/O Health ($pipeline)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processed Events I/O Rate ($instance)  (events/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 117 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "avg((irate(logstash_stats_pipeline_events_out{instance=~'$instance',pipeline=~\"$pipeline\"}[$__range])/irate(logstash_stats_pipeline_events_duration{instance=~'$instance',pipeline=~\"$pipeline\"}[$__range]))*1000) by (instance, pipeline)",
     "legendFormat": "Overall Rate for {{instance}} ({{pipeline}})"
    },
    {
     "expr": "avg((irate(logstash_stats_pipeline_plugin_events_out{instance=~'$instance',pipeline=~\"$pipeline\",plugin_type='output'}[$__range])/irate(logstash_stats_pipeline_plugin_events_duration{instance=~'$instance',pipeline=~\"$pipeline\",plugin_type='output'}[$__range])*1000) < 100000) by (instance, pipeline)",
     "legendFormat": "Outputs Rate for {{instance}} ({{pipeline}})"
    },
    {
     "expr": "avg((irate(logstash_stats_pipeline_queue_events_count{instance=~'$instance',pipeline=~\"$pipeline\",plugin_type='input'}[$__range])/irate(logstash_stats_pipeline_events_queue_push_duration{instance=~'$instance',pipeline=~\"$pipeline\",plugin_type='input'}[$__range]))*1000) by (instance, pipeline)",
     "legendFormat": "Input Queue Pressure for {{instance}} ({{pipeline}})"
    }
   ]
  }
 ]
}