{{/*
MIT License

(C) Copyright 2021-2022 Hewlett Packard Enterprise Development LP

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/}}
{{- if and (index .Values "customRules" "create") (index .Values "customRules" "rules" "postgresql") }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: {{ printf "%s-%s" (include "cray-sysmgmt-health.fullname" .) "postgresql-prometheus-alert.rules" | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "cray-sysmgmt-health.name" . }}
{{ include "cray-sysmgmt-health.labels" . | indent 4 }}
{{- if (index .Values "customRules" "labels") }}
{{ toYaml (index .Values "customRules" "labels") | indent 4 }}
{{- end }}
{{- if (index .Values "customRules" "annotations") }}
  annotations:
{{ toYaml (index .Values "customRules" "annotations") | indent 4 }}
{{- end }}
spec:
  groups:
  - name: PostgreSQL-status
    rules:
    - alert: PostgresqlDown
      expr: pg_up == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: 'Postgresql down (instance "{{`{{ $labels.instance }}`}}")'
        description: 'Postgresql instance is down  VALUE = "{{`{{ $value }}`}}"  LABELS: "{{`{{ $labels }}`}}"'
    - alert: PostgresqlExporterError
      expr: pg_exporter_last_scrape_error > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: 'Postgresql exporter error (instance "{{`{{ $labels.instance }}`}}")'
        description: 'Postgresql exporter is showing errors. A query may be buggy in query.yaml  VALUE = "{{`{{ $value }}`}}"  LABELS: "{{`{{ $labels }}`}}"'
    - alert: PostgresqlTooManyConnections
      expr: sum by (datname) (pg_stat_activity_count{datname!~'template.*|postgres'}) > pg_settings_max_connections * 0.9
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: 'Postgresql too many connections (instance "{{`{{ $labels.instance }}`}}")'
        description: 'PostgreSQL instance has too many connections  VALUE = "{{`{{ $value }}`}}"  LABELS: "{{`{{ $labels }}`}}"'
    - alert: PostgresqlNotEnoughConnections
      expr: sum by (datname) (pg_stat_activity_count{datname!~'template.*|postgres'}) < 5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: 'Postgresql not enough connections (instance "{{`{{ $labels.instance }}`}}")'
        description: 'PostgreSQL instance should have more connections (> 5)  VALUE = "{{`{{ $value }}`}}"  LABELS: "{{`{{ $labels }}`}}"'
    - alert: PostgresqlDeadLocks
      expr: rate(pg_stat_database_deadlocks{datname!~'template.*|postgres'}[1m]) > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: 'Postgresql dead locks (instance "{{`{{ $labels.instance }}`}}")'
        description: 'PostgreSQL has dead-locks  VALUE = "{{`{{ $value }}`}}"  LABELS: "{{`{{ $labels }}`}}"'
    - alert: PostgresqlHighRollbackRate
      expr: rate(pg_stat_database_xact_rollback{datname!~'template.*'}[3m]) / rate(pg_stat_database_xact_commit{datname!~'template.*'}[3m]) > 0.02
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: 'Postgresql high rollback rate (instance "{{`{{ $labels.instance }}`}}")'
        description: 'Ratio of transactions being aborted compared to committed is > 2 %  VALUE = "{{`{{ $value }}`}}"  LABELS: "{{`{{ $labels }}`}}"'
    - alert: PostgresqlTooManyLocksAcquired
      expr: ((sum (pg_locks_count)) / (pg_settings_max_locks_per_transaction * pg_settings_max_connections)) > 0.20
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: 'Postgresql too many locks acquired (instance "{{`{{ $labels.instance }}`}}")'
        description: 'Too many locks acquired on the database. If this alert happens frequently, we may need to increase the postgres setting max_locks_per_transaction.  VALUE = "{{`{{ $value }}`}}"  LABELS: "{{`{{ $labels }}`}}"'
    - alert: PostgresqlInactiveReplicationSlot
      expr: pg_replication_slots_active == 0
      for: 5m
      labels:
        severity: warning
      annotations:
        description: 'Replication Slot "{{`{{ $labels.slot_name }}`}}" is not active which may cause this replica to be out of sync with master.'
        summary: 'Postgresql replication slot is inactive.'
    - alert: PostgresqlReplicationLagSMA
      expr: pg_stat_replication_pg_wal_lsn_diff{namespace='sma'} > 1e+9
      for: 5m
      labels:
        severity: warning
      annotations:
        description: 'Replica "{{`{{ $labels.application_name }}`}}" is lagging behind master "{{`{{ $labels.pod }}`}}" by "{{`{{ $value }}`}}" bytes.'
        summary: 'Postgresql replication lag on replica "{{`{{ $labels.application_name }}`}}"'
    - alert: PostgresqlReplicationLagServices
      expr: pg_stat_replication_pg_wal_lsn_diff{namespace!='sma'} > 3e+8
      for: 5m
      labels:
        severity: warning
      annotations:
        description: 'Replica "{{`{{ $labels.application_name }}`}}" is lagging behind master "{{`{{ $labels.pod }}`}}" by "{{`{{ $value }}`}}" bytes.'
        summary: 'Postgresql replication lag on replica "{{`{{ $labels.application_name }}`}}"'
    - alert: PostgresqlFollowerReplicationLagSMA
      expr: pg_replication_slots_pg_wal_lsn_diff{namespace='sma'} > 1e+9
      for: 5m
      labels:
        severity: warning
      annotations:
        description: 'Replica from follower "{{`{{ $labels.application_name }}`}}" is lagging behind master "{{`{{ $labels.pod }}`}}" by "{{`{{ $value }}`}}" bytes.'
        summary: 'Postgresql replication lag from follower on replica "{{`{{ $labels.application_name }}`}}"'
    - alert: PostgresqlFollowerReplicationLagServices
      expr: pg_replication_slots_pg_wal_lsn_diff{namespace!='sma'} > 3e+8
      for: 5m
      labels:
        severity: warning
      annotations:
        description: 'Replica from follower "{{`{{ $labels.application_name }}`}}" is lagging behind master "{{`{{ $labels.pod }}`}}" by "{{`{{ $value }}`}}" bytes.'
        summary: 'Postgresql replication lag from follower on replica "{{`{{ $labels.application_name }}`}}"'
    - alert: PostgresqlPVCVolumeFull
      expr: kubelet_volume_stats_available_bytes{persistentvolumeclaim=~"pgdata-.+-postgres-([0-9]|.+-[0-9])",job="kubelet"}/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~"pgdata-.+-postgres-([0-9]|.+-[0-9])",job="kubelet"} <0.05
      for: 1h
      labels:
        severity: critical
      annotations:
        description: 'Postgresql PVC Volume claimed by {{`{{ $labels.persistentvolumeclaim }}`}} in Namespace {{`{{ $labels.namespace }}`}} is less than 5%.  VALUE = "{{`{{ $value }}`}}"  LABELS: "{{`{{ $labels }}`}}"'
        summary: 'Postgresql PVC Volume Full (instance "{{`{{ $labels.instance }}`}}")'
{{- end }}
