{
 "title": "Ceph - Host Overview",
 "tags": [
  "ceph-node-exporter",
  "node-exporter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "osd_hosts",
    "query": {
     "query": "label_values(ceph_osd_metadata, public_addr)"
    }
   },
   {
    "name": "mon_hosts",
    "query": {
     "query": "label_values(ceph_mon_metadata, ceph_daemon)"
    }
   },
   {
    "name": "mds_hosts",
    "query": {
     "query": "label_values(ceph_mds_inodes, ceph_daemon)"
    }
   },
   {
    "name": "rgw_hosts",
    "query": {
     "query": "label_values(ceph_rgw_qlen, ceph_daemon)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OSD Hosts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (hostname) (ceph_osd_metadata))"
    }
   ]
  },
  {
   "title": "AVG CPU Busy",
   "type": "stat",
   "description": "Average CPU busy across all hosts (OSD, RGW, MON etc) within the cluster",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(  1 - (    avg by(instance)       (irate(node_cpu_seconds_total{mode='idle',instance=~\"($osd_hosts).*\"}[1m]) or       irate(node_cpu{mode='idle',instance=~\"($osd_hosts).*\"}[1m]))    )  )"
    }
   ]
  },
  {
   "title": "AVG RAM Utilization",
   "type": "stat",
   "description": "Average Memory Usage across all hosts in the cluster (excludes buffer/cache usage)",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (((node_memory_MemTotal{instance=~\"($osd_hosts).*\"} or node_memory_MemTotal_bytes{instance=~\"($osd_hosts).*\"})- (  (node_memory_MemFree{instance=~\"($osd_hosts).*\"} or node_memory_MemFree_bytes{instance=~\"($osd_hosts).*\"})  +   (node_memory_Cached{instance=~\"($osd_hosts).*\"} or node_memory_Cached_bytes{instance=~\"($osd_hosts).*\"}) +   (node_memory_Buffers{instance=~\"($osd_hosts).*\"} or node_memory_Buffers_bytes{instance=~\"($osd_hosts).*\"}) +  (node_memory_Slab{instance=~\"($osd_hosts).*\"} or node_memory_Slab_bytes{instance=~\"($osd_hosts).*\"})  )) / (node_memory_MemTotal{instance=~\"($osd_hosts).*\"} or node_memory_MemTotal_bytes{instance=~\"($osd_hosts).*\"} ))"
    }
   ]
  },
  {
   "title": "Physical IOPS",
   "type": "stat",
   "description": "IOPS Load at the device as reported by the OS on all OSD hosts",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum ((irate(node_disk_reads_completed{instance=~\"($osd_hosts).*\"}[5m]) or irate(node_disk_reads_completed_total{instance=~\"($osd_hosts).*\"}[5m]) )  + (irate(node_disk_writes_completed{instance=~\"($osd_hosts).*\"}[5m]) or irate(node_disk_writes_completed_total{instance=~\"($osd_hosts).*\"}[5m])))"
    }
   ]
  },
  {
   "title": "AVG Disk Utilization",
   "type": "stat",
   "description": "Average Disk utilization for all OSD data devices (i.e. excludes journal/WAL)",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (  label_replace((irate(node_disk_io_time_ms{instance=~\"($osd_hosts).*\"}[5m]) / 10 ) or   (irate(node_disk_io_time_seconds_total{instance=~\"($osd_hosts).*\"}[5m]) * 100), \"instance\", \"$1\", \"instance\", \"([^:.]*)\"  ) *  on(device) group_left(ceph_daemon) label_replace(label_replace(count by (device)(sum by (device) (ceph_disk_occupation)), \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"))"
    }
   ]
  },
  {
   "title": "Network Load",
   "type": "stat",
   "description": "Total send/receive network load across all hosts in the ceph cluster",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (  irate(node_network_receive_bytes{instance=~\"($osd_hosts).*\",device!=\"lo\"}[1m]) or  irate(node_network_receive_bytes_total{instance=~\"($osd_hosts).*\",device!=\"lo\"}[1m])  ) +sum (  irate(node_network_transmit_bytes{instance=~\"($osd_hosts).*\",device!=\"lo\"}[1m]) or  irate(node_network_transmit_bytes_total{instance=~\"($osd_hosts).*\",device!=\"lo\"}[1m])  )"
    }
   ]
  },
  {
   "title": "CPU Busy - Top 10 Hosts",
   "type": "timeseries",
   "description": "Show the top 10 busiest hosts by cpu",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10,( 1 - (    avg by(instance)       (irate(node_cpu_seconds_total{mode='idle',instance=~\"($osd_hosts).*\"}[1m]) or       irate(node_cpu{mode='idle',instance=~\"($osd_hosts).*\"}[1m]))    )  ))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Load - Top 10 Hosts",
   "type": "timeseries",
   "description": "Top 10 hosts by network load",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10, (sum by(instance) (  (  irate(node_network_receive_bytes{instance=~\"($osd_hosts).*\",device!=\"lo\"}[1m]) or  irate(node_network_receive_bytes_total{instance=~\"($osd_hosts).*\",device!=\"lo\"}[1m])  ) +  (  irate(node_network_transmit_bytes{instance=~\"($osd_hosts).*\",device!=\"lo\"}[1m]) or  irate(node_network_transmit_bytes_total{instance=~\"($osd_hosts).*\",device!=\"lo\"}[1m])  ))  ))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}