{
 "title": "Ceph - OSD Overview",
 "tags": [ "ceph-exporter" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "OSD Read Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg (irate(ceph_osd_op_r_latency_sum[1m]) / on (ceph_daemon) irate(ceph_osd_op_r_latency_count[1m]) * 1000)",
     "legendFormat": "AVG read"
    },
    {
     "expr": "max (irate(ceph_osd_op_r_latency_sum[1m]) / on (ceph_daemon) irate(ceph_osd_op_r_latency_count[1m]) * 1000)",
     "legendFormat": "MAX read"
    },
    {
     "expr": "quantile(0.95,  (irate(ceph_osd_op_r_latency_sum[1m]) / on (ceph_daemon) irate(ceph_osd_op_r_latency_count[1m]) * 1000))",
     "legendFormat": "@95%ile"
    }
   ]
  },
  {
   "title": "Highest READ Latencies",
   "type": "table",
   "description": "This table shows the osd's that are delivering the 10 highest read latencies within the cluster",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,  (sort(    (irate(ceph_osd_op_r_latency_sum[1m]) / on (ceph_daemon) irate(ceph_osd_op_r_latency_count[1m]) * 1000)  )))"
    }
   ]
  },
  {
   "title": "OSD Write Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg (irate(ceph_osd_op_w_latency_sum[1m]) / on (ceph_daemon) irate(ceph_osd_op_w_latency_count[1m]) * 1000)",
     "legendFormat": "AVG write"
    },
    {
     "expr": "max (irate(ceph_osd_op_w_latency_sum[1m]) / on (ceph_daemon) irate(ceph_osd_op_w_latency_count[1m]) * 1000)",
     "legendFormat": "MAX write"
    },
    {
     "expr": "quantile(0.95, (irate(ceph_osd_op_w_latency_sum[1m]) / on (ceph_daemon) irate(ceph_osd_op_w_latency_count[1m]) * 1000))",
     "legendFormat": "@95%ile write"
    }
   ]
  },
  {
   "title": "Highest WRITE Latencies",
   "type": "table",
   "description": "This table shows the osd's that are delivering the 10 highest write latencies within the cluster",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,  (sort(    (irate(ceph_osd_op_w_latency_sum[1m]) / on (ceph_daemon) irate(ceph_osd_op_w_latency_count[1m]) * 1000)  )))"
    }
   ]
  },
  {
   "title": "OSD Types Summary",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(device_class) (ceph_osd_metadata)",
     "legendFormat": "{{device_class}}"
    }
   ]
  },
  {
   "title": "OSD Objectstore Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_bluefs_wal_total_bytes)",
     "legendFormat": "bluestore"
    },
    {
     "expr": "count(ceph_osd_metadata) - count(ceph_bluefs_wal_total_bytes)",
     "legendFormat": "filestore"
    },
    {
     "expr": "absent(ceph_bluefs_wal_total_bytes)*count(ceph_osd_metadata)",
     "legendFormat": "filestore"
    }
   ]
  },
  {
   "title": "OSD Size Summary",
   "type": "piechart",
   "description": "The pie chart shows the various OSD sizes used within the cluster",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_stat_bytes < 1099511627776)",
     "legendFormat": "<1 TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes >= 1099511627776 < 2199023255552)",
     "legendFormat": "<2 TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes >= 2199023255552 < 3298534883328)",
     "legendFormat": "<3TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes >= 3298534883328 < 4398046511104)",
     "legendFormat": "<4TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes >= 4398046511104 < 6597069766656)",
     "legendFormat": "<6TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes >= 6597069766656 < 8796093022208)",
     "legendFormat": "<8TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes >= 8796093022208 < 10995116277760)",
     "legendFormat": "<10TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes >= 10995116277760 < 13194139533312)",
     "legendFormat": "<12TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes >= 13194139533312)",
     "legendFormat": "12TB+"
    }
   ]
  },
  {
   "title": "Distribution of PGs per OSD",
   "type": "graph",
   "description": "Each bar indicates the number of OSD's that have a PG count in a specific range as shown on the x axis.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "# of OSDs" }
   ],
   "targets": [
    { "expr": "ceph_osd_numpg", "legendFormat": "PGs per OSD" }
   ]
  },
  {
   "title": "R/W Profile",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Read/Write Profile",
   "type": "timeseries",
   "description": "Show the read/write workload profile overtime",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(irate(ceph_pool_rd[$__rate_interval])))",
     "legendFormat": "Reads"
    },
    {
     "expr": "round(sum(irate(ceph_pool_wr[$__rate_interval])))",
     "legendFormat": "Writes"
    }
   ]
  }
 ]
}