{
 "title": "Ceph - RGW Instance Detail",
 "tags": [ "ceph-exporter" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "rgw_servers",
    "query": {
     "query": "label_values(ceph_rgw_req, ceph_daemon)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RGW Host Detail : $rgw_servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$rgw_servers GET/PUT Latencies",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (ceph_daemon) (rate(ceph_rgw_get_initial_lat_sum{ceph_daemon=~\"($rgw_servers)\"}[1m]) / rate(ceph_rgw_get_initial_lat_count{ceph_daemon=~\"($rgw_servers)\"}[1m]))",
     "legendFormat": "GET {{ceph_daemon}}"
    },
    {
     "expr": "sum by (ceph_daemon)(rate(ceph_rgw_put_initial_lat_sum{ceph_daemon=~\"($rgw_servers)\"}[1m]) / rate(ceph_rgw_put_initial_lat_count{ceph_daemon=~\"($rgw_servers)\"}[1m]))",
     "legendFormat": "PUT {{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "Bandwidth by HTTP Operation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(ceph_rgw_get_b{ceph_daemon=~\"[[rgw_servers]]\"}[1m])",
     "legendFormat": "GETs {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_put_b{ceph_daemon=~\"[[rgw_servers]]\"}[1m])",
     "legendFormat": "PUTs {{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "HTTP Request Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ceph_rgw_failed_req{ceph_daemon=~\"[[rgw_servers]]\"}[1m])",
     "legendFormat": "Requests Failed {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_get{ceph_daemon=~\"[[rgw_servers]]\"}[1m])",
     "legendFormat": "GETs {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_put{ceph_daemon=~\"[[rgw_servers]]\"}[1m])",
     "legendFormat": "PUTs {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_req{ceph_daemon=~\"[[rgw_servers]]\"}[1m]) -  (rate(ceph_rgw_get{ceph_daemon=~\"[[rgw_servers]]\"}[1m]) +   rate(ceph_rgw_put{ceph_daemon=~\"[[rgw_servers]]\"}[1m]))",
     "legendFormat": "Other {{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "Workload Breakdown",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(ceph_rgw_failed_req{ceph_daemon=~\"[[rgw_servers]]\"}[1m])",
     "legendFormat": "Failures {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_get{ceph_daemon=~\"[[rgw_servers]]\"}[1m])",
     "legendFormat": "GETs {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_put{ceph_daemon=~\"[[rgw_servers]]\"}[1m])",
     "legendFormat": "PUTs {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_req{ceph_daemon=~\"[[rgw_servers]]\"}[1m]) -  (rate(ceph_rgw_get{ceph_daemon=~\"[[rgw_servers]]\"}[1m]) +   rate(ceph_rgw_put{ceph_daemon=~\"[[rgw_servers]]\"}[1m]))",
     "legendFormat": "Other (DELETE,LIST) {{ceph_daemon}}"
    }
   ]
  }
 ]
}