{
 "title": "Ceph - RBD Overview",
 "tags": [ "no-results" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(irate(ceph_rbd_write_ops[1m])))",
     "legendFormat": "Writes"
    },
    {
     "expr": "round(sum(irate(ceph_rbd_read_ops[1m])))",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "round(sum(irate(ceph_rbd_write_bytes[1m])))",
     "legendFormat": "Write"
    },
    {
     "expr": "round(sum(irate(ceph_rbd_read_bytes[1m])))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "round(sum(irate(ceph_rbd_write_latency_sum[1m])) / sum(irate(ceph_rbd_write_latency_count[1m])))",
     "legendFormat": "Write"
    },
    {
     "expr": "round(sum(irate(ceph_rbd_read_latency_sum[1m])) / sum(irate(ceph_rbd_read_latency_count[1m])))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Highest IOPS",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, (sort((irate(ceph_rbd_write_ops[1h]) + on(image, pool, namespace) irate(ceph_rbd_read_ops[1h])))))"
    }
   ]
  },
  {
   "title": "Highest Throughput",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sort(sum(irate(ceph_rbd_read_bytes[1h]) + irate(ceph_rbd_write_bytes[1h])) by (pool, image, namespace)))"
    }
   ]
  },
  {
   "title": "Highest Latency",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,  sum(    irate(ceph_rbd_write_latency_sum[1h]) / clamp_min(irate(ceph_rbd_write_latency_count[1h]), 1) +    irate(ceph_rbd_read_latency_sum[1h]) / clamp_min(irate(ceph_rbd_read_latency_count[1h]), 1)  ) by (pool, image, namespace))"
    }
   ]
  }
 ]
}