{
 "title": "SMA-Flow Service Stats",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Pod",
    "query": {
     "query": "label_values(flow_consumed_messages,pod)"
    }
   },
   {
    "name": "Endpoint",
    "query": {
     "query": "label_values(flow_consumed_messages,endpoint)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Flow Consumed Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "flow_consumed_messages{pod=~\"$Pod\", endpoint=~\"$Endpoint\"}",
     "legendFormat": "{{pod}}-{{endpoint}}"
    }
   ]
  },
  {
   "title": "Flow Transformed Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "flow_transformed_messages{pod=~\"$Pod\", endpoint=~\"$Endpoint\"}",
     "legendFormat": "{{pod}}-{{endpoint}}"
    }
   ]
  },
  {
   "title": "Flow Samples Parsed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "flow_samples_parsed{pod=~\"$Pod\", endpoint=~\"$Endpoint\"}",
     "legendFormat": "{{pod}}-{{endpoint}}"
    }
   ]
  },
  {
   "title": "Flow Samples Written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "flow_samples_written{pod=~\"$Pod\", endpoint=~\"$Endpoint\"}",
     "legendFormat": "{{pod}}-{{endpoint}}"
    }
   ]
  },
  {
   "title": "Flow Transform Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "flow_transform_errors{pod=~\"$Pod\", endpoint=~\"$Endpoint\"}",
     "legendFormat": "{{pod}}-{{endpoint}}"
    }
   ]
  },
  {
   "title": "Flow Flush Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "flow_flush_errors{pod=~\"$Pod\", endpoint=~\"$Endpoint\"}",
     "legendFormat": "{{pod}}-{{endpoint}}"
    }
   ]
  },
  {
   "title": "Flow Write Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "flow_write_errors{pod=~\"$Pod\", endpoint=~\"$Endpoint\"}",
     "legendFormat": "{{pod}}-{{endpoint}}"
    }
   ]
  },
  {
   "title": "Flow Reconnect Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "flow_reconnect_attempts{pod=~\"$Pod\", endpoint=~\"$Endpoint\"}",
     "legendFormat": "{{pod}}-{{endpoint}}"
    }
   ]
  },
  {
   "title": "Flow Line Too Long",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "flow_line_too_long{pod=~\"$Pod\", endpoint=~\"$Endpoint\"}",
     "legendFormat": "{{pod}}-{{endpoint}}"
    }
   ]
  }
 ]
}