{
 "title": "Kafka Connect",
 "description": "Monitor Apache Kafka Connect",
 "tags": [ "kafka" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_connect_app_info{job=\"sysmgmt-health/cray-sysmgmt-health-kubernetes-pods\", },instance)"
    }
   },
   {
    "name": "connector",
    "label": "Connector name",
    "query": {
     "query": "label_values(kafka_connect_connector_task_metrics_pause_ratio{job=\"sysmgmt-health/cray-sysmgmt-health-kubernetes-pods\"},connector)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tasks Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_total_task_count{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_running_task_count{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Paused",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_paused_task_count{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_failed_task_count{app=\"kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Unassigned",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_unassigned_task_count{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Destroyed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_destroyed_task_count{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Connector repartition per status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_connect_connector_metrics{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\",status=\"running\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum (kafka_connect_connector_metrics{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\",status=\"stopped\"})",
     "legendFormat": "stopped"
    },
    {
     "expr": "sum (kafka_connect_connector_metrics{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\",status=\"paused\"})",
     "legendFormat": "paused"
    }
   ]
  },
  {
   "title": "Task repartition per status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_running_task_count{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_failed_task_count{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_paused_task_count{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "paused"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_unassigned_task_count{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "unassigned"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_destroyed_task_count{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "destroyed"
    }
   ]
  },
  {
   "title": "Status of connectors",
   "type": "timeseries",
   "description": "Status of connectors over time",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (kafka_connect_connector_metrics{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\",status!=\"\"}) by (status) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Status of tasks",
   "type": "timeseries",
   "description": "Status of tasks over time",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_running_task_count{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_failed_task_count{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_paused_task_count{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "paused"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_destroyed_task_count{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "destroyed"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_unassigned_task_count{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "unassigned"
    }
   ]
  },
  {
   "title": "Connect Worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connect Worker",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "kafka_connect_app_info{app=\"cp-kafka-connect\",instance=~\"$instance\",client_id!=\"\",start_time_ms!=\"\"}"
    },
    {
     "expr": "kafka_connect_app_info{app=\"cp-kafka-connect\",instance=~\"$instance\",client_id!=\"\",version!=\"\"}"
    },
    {
     "expr": "sum by (instance) (kafka_connect_connect_worker_metrics_connector_count{app=\"cp-kafka-connect\",instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (instance) (kafka_connect_connect_worker_metrics_connector_startup_success_total{app=\"cp-kafka-connect\",instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (instance) (kafka_connect_connect_worker_metrics_connector_startup_failure_total{app=\"cp-kafka-connect\",instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (instance) (kafka_connect_connect_worker_metrics_task_count{app=\"cp-kafka-connect\",instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (instance) (kafka_connect_connect_worker_metrics_task_startup_success_total{app=\"cp-kafka-connect\",instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (instance) (kafka_connect_connect_worker_metrics_task_startup_failure_total{app=\"cp-kafka-connect\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Network IO Rate",
   "type": "timeseries",
   "description": "Average number of network operations (reads or writes) on all connections per second",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_network_io_rate{app=\"cp-kafka-connect\",instance=~\"$instance\",client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Incoming Byte Rate",
   "type": "timeseries",
   "description": "Bytes per second read off all sockets",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_incoming_byte_rate{app=\"cp-kafka-connect\",instance=~\"$instance\",client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Outgoing Byte Rate",
   "type": "timeseries",
   "description": "Average number of outgoing bytes sent per second to all servers",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_outgoing_byte_rate{app=\"cp-kafka-connect\",instance=~\"$instance\",client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Current number of active connections",
   "type": "timeseries",
   "description": "Current number of active connections",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "connections" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_connection_count{app=\"cp-kafka-connect\",instance=~\"$instance\",client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Failed authentication connections",
   "type": "timeseries",
   "description": "Connections that failed authentication",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "connections" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_failed_authentication_total{app=\"cp-kafka-connect\",instance=~\"$instance\",client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Success authentication connections",
   "type": "timeseries",
   "description": "Connections that were successfully authenticated using SASL or SSL",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "connections" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_successful_authentication_rate{app=\"cp-kafka-connect\",instance=~\"$instance\",client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Average number of requests",
   "type": "timeseries",
   "description": "Average number of requests sent per second",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_request_rate{app=\"cp-kafka-connect\",instance=~\"$instance\",client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Responses received and sent",
   "type": "timeseries",
   "description": "Responses received and sent per second",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_response_rate{app=\"cp-kafka-connect\",instance=~\"$instance\",client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "IO Ratio",
   "type": "timeseries",
   "description": "Fraction of time the I/O thread spent doing I/O",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_io_ratio{app=\"cp-kafka-connect\",instance=~\"$instance\",client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Connector details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connectors",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(kafka_connect_connector_metrics{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\",status!=\"\"}, \"status\", \"1\", \"status\", \"running\"), \"status\", \"2\", \"status\", \"paused\"), \"status\", \"3\", \"status\", \"stopped\")"
    },
    {
     "expr": "kafka_connect_connector_metrics{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\",connector_type!=\"\"}"
    },
    {
     "expr": "kafka_connect_connector_metrics{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\",connector_version!=\"\"}"
    },
    {
     "expr": "kafka_connect_connector_metrics{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\",connector_class!=\"\"}"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_failed_task_count{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_paused_task_count{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_destroyed_task_count{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_unassigned_task_count{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Rebalances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rebalances average time",
   "type": "timeseries",
   "description": "Rebalances average time",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_rebalance_metrics_rebalance_avg_time_ms{app=\"cp-kafka-connect\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "($instance) Time since last rebalance ",
   "type": "stat",
   "description": "Time since last rebalance",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 68 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "clockms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_rebalance_metrics_time_since_last_rebalance_ms{app=\"cp-kafka-connect\",instance=~\"$instance\"} >= 0"
    }
   ]
  },
  {
   "title": "Task metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Batch Size Average",
   "type": "timeseries",
   "description": "Average size of the batches processed by the connector",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_batch_size_avg{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Batch Size Max",
   "type": "timeseries",
   "description": "Maximum size of the batches processed by the connector",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_batch_size_max{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Offset commit success percentage",
   "type": "timeseries",
   "description": "Average percentage of the task’s offset commit attempts that succeeded",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_offset_commit_success_percentage{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Offset commit Average Time",
   "type": "timeseries",
   "description": "The average time in milliseconds taken by this task to commit offsets",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_offset_commit_avg_time_ms{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Running ratio",
   "type": "timeseries",
   "description": "The fraction of time this task has spent in the running state.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_running_ratio{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Task Errors metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total record failures",
   "type": "timeseries",
   "description": "Total number of failures seen by task",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_total_record_failures{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total record errors",
   "type": "timeseries",
   "description": "Total number of errors seen by task",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_total_record_errors{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total record skipped",
   "type": "timeseries",
   "description": "Total number of records skipped by task",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_total_records_skipped{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total errors logged",
   "type": "timeseries",
   "description": "The number of messages that was logged into either the dead letter queue or with Log4j",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_total_errors_logged{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total retries",
   "type": "timeseries",
   "description": "Total number of retries made by task",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_total_retries{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Dead letter queue Produce requests",
   "type": "timeseries",
   "description": "Number of produce requests to the dead letter queue",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_deadletterqueue_produce_requests{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Dead letter queue Produce requests",
   "type": "timeseries",
   "description": "Number of produce requests to the dead letter queue",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_deadletterqueue_produce_requests{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Sink metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Partition Count",
   "type": "timeseries",
   "description": "The number of topic partitions assigned to this task belonging to the named sink connector in this worker.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_sink_task_metrics_partition_count{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Put Batch Average time",
   "type": "timeseries",
   "description": "The average time in milliseconds taken by this task to put a batch of sinks records",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_sink_task_metrics_put_batch_avg_time_ms{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Put Batch Max time",
   "type": "timeseries",
   "description": "The maximum time in milliseconds taken by this task to put a batch of sinks records",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_sink_task_metrics_put_batch_max_time_ms{app=\"cp-kafka-connect\",instance=~\"$instance\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  }
 ]
}