{
 "title": "Zookeeper",
 "tags": [ "kafka" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Health Check",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of ZNodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(zookeeper_inmemorydatatree_nodecount{job=\"sysmgmt-health/kafka-resources-metrics\"})"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "timeseries",
   "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "zookeeper_outstandingrequests{job=\"sysmgmt-health/kafka-resources-metrics\"}",
     "legendFormat": "{{server_id}}:{{member_type}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Alive Connections",
   "type": "stat",
   "description": "Number of Alive Connections",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zookeeper_numaliveconnections{job=\"sysmgmt-health/kafka-resources-metrics\"})"
    }
   ]
  },
  {
   "title": "Number of Watchers",
   "type": "stat",
   "description": "Number of Watchers",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(zookeeper_inmemorydatatree_watchcount{job=\"sysmgmt-health/kafka-resources-metrics\"})"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"sysmgmt-health/kafka-resources-metrics\", container=\"zookeeper\"}[5m])*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_used_bytes{job=\"sysmgmt-health/kafka-resources-metrics\", container=\"zookeeper\"})",
     "legendFormat": "Used:{{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_max{job=\"sysmgmt-health/kafka-resources-metrics\", container=\"zookeeper\", area=\"heap\"}",
     "legendFormat": "Max:{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"sysmgmt-health/kafka-resources-metrics\", container=\"zookeeper\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Latency - Minimum",
   "type": "timeseries",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "zookeeper_minrequestlatency{job=\"sysmgmt-health/kafka-resources-metrics\"} * zookeeper_ticktime",
     "legendFormat": "{{server_id}}:{{member_type}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Request Latency - Average",
   "type": "timeseries",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "zookeeper_avgrequestlatency{job=\"sysmgmt-health/kafka-resources-metrics\"} * zookeeper_ticktime",
     "legendFormat": "{{server_id}}:{{member_type}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Request Latency - Maximum",
   "type": "timeseries",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "zookeeper_maxrequestlatency{job=\"sysmgmt-health/kafka-resources-metrics\"} * zookeeper_ticktime",
     "legendFormat": "{{server_id}}:{{member_type}} ({{instance}})"
    }
   ]
  }
 ]
}