#
# MIT License
#
# (C) Copyright 2022-2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cray-sysmgmt-health.fullname" . }}-grok-exporter
  namespace: {{ .Release.Namespace }}
data:
  config.yml: |-
    global:
      config_version: 3
    input:
      type: file
      paths: 
      - /logs/goss_tests/*
      fail_on_missing_logfile: false
    grok_patterns:
      - 'TIMESTAMP [0-9]{8}_[0-9]{6}.[0-9]{6}'
      - 'PRODUCT CSM|SMA|SMF'
      - 'SCRIPT [aA-zZ._].*'
      - 'DESC [aA-zZ].*'
      - 'NUM [0-9].*'
      - 'TIME [0-9].[0-9]{9}'
      - 'NODE ncn-(s|w|m)[0-9]{3}'
      - 'CODE 0|1'
      - 'RESULT PASS|FAIL|SKIP|UNKNOWN'
      - 'SUITE [aA-zZ-].*'
    metrics:
      - type: gauge
        name: goss_tests
        help: GOSS TESTS
        match: '{"log_timestamp": "%{TIMESTAMP:tstmp}", "Product": "%{PRODUCT:prod}", "log_script": "%{SCRIPT:scrip}", "log_message": "Test result", "Description": "%{DESC:desc}", "Execution Time \(nanoseconds\)": %{NUM:ns}, "Execution Time \(seconds\)": %{TIME:time}, "Node": "%{NODE:node}", "Result Code": %{CODE:code}, "Result String": "%{RESULT:res}", "Source": ".*\/%{SUITE:suite}", "Test Name": "%{DESC:name}", "Test Summary": "%{DESC:sum}"}'
        value: '{{`{{.time}}`}}'
        labels:
          Timestamp: '{{`{{.tstmp}}`}}'
          Product: '{{`{{.prod}}`}}'
          Script: '{{`{{.scrip}}`}}'
          Description: '{{`{{.desc}}`}}'
          Execution_raw: '{{`{{.ns}}`}}'
          Execution_time: '{{`{{.time}}`}}'
          Node: '{{`{{.node}}`}}'
          Code: '{{`{{.code}}`}}'
          Result: '{{`{{.res}}`}}'
          Suite: '{{`{{.suite}}`}}'
          Test_name: '{{`{{.name}}`}}'
          Test_summary: '{{`{{.sum}}`}}'
    server:
     port: 9144
