#
# MIT License
#
# (C) Copyright 2022-2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cray-sysmgmt-health.fullname" . }}-grok-exporter
  labels:
    app: grok-exporter
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grok-exporter
  strategy:
    rollingUpdate:
      maxSurge: 35%
      maxUnavailable: 35%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grok-exporter
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchFields:
              - key: metadata.name
                operator: In
                values:
                - ncn-m001
            - matchFields:
              - key: metadata.name
                operator: In
                values:
                - ncn-m002
            - matchFields:
              - key: metadata.name
                operator: In
                values:
                - ncn-m003
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - grok-exporter
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: grok-exporter
          image: {{ .Values.grokExporter.image.repository }}:{{ .Values.grokExporter.image.tag }}
          imagePullPolicy: {{ .Values.grokExporter.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9144
              protocol: TCP
          volumeMounts:
            - name: grok-config-volume
              mountPath: /etc/grok_exporter
            - name: logs
              mountPath: /logs/goss_tests
      volumes:
        - name: grok-config-volume
          configMap:
            name: {{ template "cray-sysmgmt-health.fullname" . }}-grok-exporter 
        - name: logs
          hostPath:
            path: /opt/cray/tests/install/logs/grok_exporter
            type: DirectoryOrCreate
      tolerations:
        - effect: "NoSchedule"
          key: node-role.kubernetes.io/master
          operator: Exists
