{
 "title": "Prometheus Remote Write",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(prometheus_build_info, instance)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_container_info{image=~\".*prometheus.*\"}, cluster)"
    }
   },
   {
    "name": "url",
    "query": {
     "query": "label_values(prometheus_remote_storage_shards{cluster=~\"$cluster\", instance=~\"$instance\"}, url)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Timestamps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Highest Timestamp In vs. Highest Timestamp Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(  prometheus_remote_storage_highest_timestamp_in_seconds{cluster=~\"$cluster\", instance=~\"$instance\"} -    ignoring(remote_name, url) group_right(instance) prometheus_remote_storage_queue_highest_sent_timestamp_seconds{cluster=~\"$cluster\", instance=~\"$instance\"})",
     "legendFormat": "{{cluster}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Rate[5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(  rate(prometheus_remote_storage_highest_timestamp_in_seconds{cluster=~\"$cluster\", instance=~\"$instance\"}[5m])  -   ignoring (remote_name, url) group_right(instance) rate(prometheus_remote_storage_queue_highest_sent_timestamp_seconds{cluster=~\"$cluster\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{cluster}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Samples",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate, in vs. succeeded or dropped [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(  prometheus_remote_storage_samples_in_total{cluster=~\"$cluster\", instance=~\"$instance\"}[5m])-   ignoring(remote_name, url) group_right(instance) rate(prometheus_remote_storage_samples_total{cluster=~\"$cluster\", instance=~\"$instance\"}[5m])-   rate(prometheus_remote_storage_samples_dropped_total{cluster=~\"$cluster\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{cluster}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Shards",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_remote_storage_shards{cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{cluster}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Max Shards",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_remote_storage_shards_max{cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{cluster}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Min Shards",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_remote_storage_shards_min{cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{cluster}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Desired Shards",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_remote_storage_shards_desired{cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{cluster}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Shard Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Shard Capacity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_remote_storage_shard_capacity{cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{cluster}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Remote storage shards",
   "type": "timeseries",
   "description": "Current number of active shards",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "prometheus_remote_storage_shards",
     "legendFormat": "shards"
    },
    {
     "expr": "prometheus_remote_storage_shards_desired",
     "legendFormat": "desired shards"
    }
   ]
  },
  {
   "title": "Segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TSDB Current Segment",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_wal_segment_current{cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{cluster}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Remote Write Current Segment",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_wal_watcher_current_segment{cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{cluster}}:{{instance}} {{consumer}}"
    }
   ]
  },
  {
   "title": "Misc. Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "50th and 95th percentiles of remote storage batch latency",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "aggregator": "p95",
     "alias": "95th Percentile",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "histogram_quantile(0.50, sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50",
     "target": "Bosun Query"
    },
    {
     "aggregator": "p95",
     "alias": "95th Percentile",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "histogram_quantile(0.95, sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95",
     "target": "Bosun Query"
    },
    {
     "aggregator": "p95",
     "alias": "95th Percentile",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "histogram_quantile(0.99, sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p99",
     "target": "Bosun Query"
    }
   ]
  },
  {
   "title": "Enqueue Retries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_enqueue_retries_total{cluster=~\"$cluster\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{cluster}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Dropped Samples",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_samples_dropped_total{cluster=~\"$cluster\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{cluster}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Failed Samples",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_samples_failed_total{cluster=~\"$cluster\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{cluster}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Pending Samples",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_remote_storage_samples_pending{cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{cluster}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Retried Samples",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_samples_retried_total{cluster=~\"$cluster\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{cluster}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  }
 ]
}