#
# MIT License
#
# (C) Copyright 2021-2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
{{- /*
MIT License
(C) Copyright [2021] Hewlett Packard Enterprise Development LP
Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

This sets the GOMAXPROCS env var on the prometheus-node-exporter pods. By
default the Go procs matches the number of CPUs, which doesn't work well when
you have 64 CPUs.

We may be able to remove this in the future. There's a PR up to the node
exporter to default to 1 proc, see
https://github.com/prometheus/node_exporter/issues/1880

This is a Helm hook because the prometheus-operator chart doesn't support
adding extra environment variables.

*/ -}}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "cray-sysmgmt-health.fullname" . }}-node-exporter-hook
  labels:
{{ include "cray-sysmgmt-health.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      name: {{ template "cray-sysmgmt-health.fullname" . }}-node-exporter-hook
      labels:
{{ include "cray-sysmgmt-health.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ template "cray-sysmgmt-health.fullname" . }}-node-exporter-hook
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: {{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}
          imagePullPolicy: {{ .Values.kubectl.image.pullPolicy }}
          command:
            - kubectl
            - set
            - env
            - daemonset
            - -n
            - sysmgmt-health
            - {{ template "cray-sysmgmt-health.fullname" . }}-prometheus-node-exporter
            - GOMAXPROCS=1
          securityContext:
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
