{{- /*
Copyright 2021 Hewlett Packard Enterprise Development LP

This is used by the node-exporter post-install Hook. The Hook needs to do a
patch operation on the cray-sysmgmt-health-prometheus-node-exporter DeamonSet.
*/ -}}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "cray-sysmgmt-health.fullname" . }}-node-exporter-patcher
rules:
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["get", "list", "patch"]

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "cray-sysmgmt-health.fullname" . }}-node-exporter-hook

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "cray-sysmgmt-health.fullname" . }}-node-exporter-patcher
subjects:
  - kind: ServiceAccount
    name: {{ template "cray-sysmgmt-health.fullname" . }}-node-exporter-hook
roleRef:
  kind: Role
  name: {{ template "cray-sysmgmt-health.fullname" . }}-node-exporter-patcher
  apiGroup: rbac.authorization.k8s.io
