{
 "title": "Hardware temperature monitoring",
 "tags": [
  "linux",
  "hwmon",
  "temperature",
  "fan speed",
  "voltage",
  "amperage",
  "power"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "# The nicest possible display of a metric...\r\nnode_hwmon_temp_celsius{instance=~\"$instance\"} \n  * on(instance,chip,sensor) group_left(label) node_hwmon_sensor_label \n  * on(instance,chip) group_left(chip_name) node_hwmon_chip_names\n# ...but it may filter out metrics that do not have a label, so as a fallback use the machine sensor name\r\n  or on(instance,chip,sensor) label_replace(node_hwmon_temp_celsius{instance=~\"$instance\"}, \"label\", \"$0\", \"sensor\", \".*\") \r\n    * on(instance,chip) group_left(chip_name) node_hwmon_chip_names\r\n  or on(instance,chip,sensor) label_replace(label_replace(node_hwmon_temp_celsius{instance=~\"$instance\"}, \"label\", \"$0\", \"sensor\", \".*\"), \"chip_name\", \"$0\", \"chip\", \".*\")"
    }
   ]
  },
  {
   "title": "Critical Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_crit_celsius{instance=~\"$instance\"}* on(instance,chip,sensor) group_left(label) (node_hwmon_sensor_label)* on(instance,chip) group_left(chip_name) (node_hwmon_chip_names) or label_replace(node_hwmon_temp_crit_celsius{instance=~\"$instance\"}, \"label\", \"$0\", \"sensor\", \".*\") * on(instance,chip) group_left(chip_name) (node_hwmon_chip_names) unless on(instance,chip,sensor) (node_hwmon_sensor_label)"
    }
   ]
  },
  {
   "title": "Maximum Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " node_hwmon_temp_max_celsius{instance=~\"$instance\"}* on(instance,chip,sensor) group_left(label) (node_hwmon_sensor_label)* on(instance,chip) group_left(chip_name) (node_hwmon_chip_names) or label_replace(node_hwmon_temp_max_celsius{instance=~\"$instance\"}, \"label\", \"$0\", \"sensor\", \".*\") * on(instance,chip) group_left(chip_name) (node_hwmon_chip_names) unless on(instance,chip,sensor) (node_hwmon_sensor_label)"
    }
   ]
  },
  {
   "title": "Critical Alarm Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_crit_alarm_celsius{instance=~\"$instance\"}* on(instance,chip,sensor) group_left(label) (node_hwmon_sensor_label)* on(instance,chip) group_left(chip_name) (node_hwmon_chip_names) or label_replace(node_hwmon_temp_crit_alarm_celsius{instance=~\"$instance\"}, \"label\", \"$0\", \"sensor\", \".*\") * on(instance,chip) group_left(chip_name) (node_hwmon_chip_names) unless on(instance,chip,sensor) (node_hwmon_sensor_label)"
    }
   ]
  }
 ]
}