#
# MIT License
#
# (C) Copyright 2021-2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
{{- if and (index .Values "customRules" "create") (index .Values "customRules" "rules" "mdraid") }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: {{ printf "%s-%s" (include "cray-sysmgmt-health.fullname" .) "mdraid-prometheus-alert.rules" | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "cray-sysmgmt-health.name" . }}
{{ include "cray-sysmgmt-health.labels" . | indent 4 }}
{{- if (index .Values "customRules" "labels") }}
{{ toYaml (index .Values "customRules" "labels") | indent 4 }}
{{- end }}
{{- if (index .Values "customRules" "annotations") }}
  annotations:
{{ toYaml (index .Values "customRules" "annotations") | indent 4 }}
{{- end }}
spec:
  groups:
  - name: MD RAID Arrays
    rules:
    - alert: MdRaidArrayGotInactive
      expr: node_md_state{state="inactive"} > 0
      for: 5m
      labels:
        severity: critical
        group: prometheus
      annotations:
        description: 'MD RAID array "{{`{{ $labels.device }}`}}" on (instance "{{`{{ $labels.instance }}`}}") is in Inactive state'
        summary: 'An MD RAID array is in Inactive state'

    - alert: MdRaidDiskFailure
      expr: node_md_disks{state="failed"} > 0
      for: 5m
      labels:
        severity: critical
        group: prometheus
      annotations:
        description: 'At least one device in MD RAID array "{{`{{ $labels.device }}`}}" on "{{`{{ $labels.instance }}`}}" has failed'
        summary: 'An MD RAID has failed'

    # Alert for Storage Nodes, which has older version of Node Exporter running
    - alert: MdRaidDegradedOlderNodeExporter
      expr: (node_md_disks - node_md_disks_active) != 0
      for: 1m
      labels:
        severity: critical
        group: prometheus
      annotations:
        description: 'An MD RAID array "{{`{{ $labels.device }}`}}" on "{{`{{ $labels.instance }}`}}" is in Degraded state: {{`{{ $value }}`}} disks failed'
        summary: 'An MD RAID array is in Degraded state'

    # Alert for Nodes, running newer version of Node Exporter running
    - alert: MdRaidDegraded
      expr: |
        node_md_disks_required - ignoring (state) (node_md_disks{state="active"}) > 0
      for: 15m
      labels:
        severity: critical
        group: prometheus
      annotations:
        description: 'An MD RAID array "{{`{{ $labels.device }}`}}" on "{{`{{ $labels.instance }}`}}" is in degraded state due to failure of {{`{{ $value }}`}} disks.'
        summary: 'An MD RAID array is in Degraded state'
{{- end }}
