#
# MIT License
#
# (C) Copyright 2021-2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
{{- if and (index .Values "customRules" "create") (index .Values "customRules" "rules" "smartmon-alerts") }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "%s-%s" (include "cray-sysmgmt-health.fullname" .) "smartmon-alerts.rules" | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "cray-sysmgmt-health.name" . }}
{{ include "cray-sysmgmt-health.labels" . | indent 4 }}
{{- if (index .Values "customRules" "labels") }}
{{ toYaml (index .Values "customRules" "labels") | indent 4 }}
{{- end }}
{{- if (index .Values "customRules" "annotations") }}
  annotations:
{{ toYaml (index .Values "customRules" "annotations") | indent 4 }}
{{- end }}
spec:
  groups:
  - name: SMART status
    rules:
    - alert: SmartUnhealthy
      annotations:
        message: 'Disk "{{`{{ $labels.disk }}`}}" on host "{{`{{ $labels.instance }}`}}" is unhealthy according to SMART'
      expr: smartmon_device_smart_healthy != 1    
      for: 5m
      labels:
        severity: critical
    - alert: SmartDisabled
      annotations:
        message: 'SMART disabled on "{{`{{ $labels.type }}`}}"  "{{`{{ $labels.disk }}`}}" '
      expr: smartmon_device_smart_available == 1 and smartmon_device_smart_enabled == 0
      for: 5m
      labels:
        severity: critical
    - alert: SmartHealth
      annotations:
        message: 'SMART unhealthy on "{{`{{ $labels.type }}`}}"  "{{`{{ $labels.disk }}`}}" '
      expr: smartmon_device_smart_healthy != 1 and smartmon_device_smart_enabled == 1
      for: 5m
      labels:
        severity: informational
    - alert: SmartDefects
      annotations:
        message: 'SMART defects grow "{{`{{ $labels.type }}`}}"  "{{`{{ $labels.disk }}`}}" '
      expr: increase(smartmon_grown_defects_count_raw_value[1d]) > 0
      for: 5m
      labels:
        severity: informational
    - alert: SmartPowerCycles
      annotations:
        message: 'Disk "{{`{{ $labels.type }}`}}" "{{`{{ $labels.disk }}`}}" power cycles "{{`{{ printf "%.0f" $value }}`}}"/day '
      expr: increase(smartmon_power_cycle_count_raw_value[1d]) > 10
      for: 5m
      labels:
        severity: informational
    - alert: SmartExpired
      annotations:
        message: '"{{`{{ $labels.type }}`}}" "{{`{{ $labels.disk }}`}}" no data for "{{`{{ printf "%.0f" $value }}`}}"min '
      expr: (time() - smartmon_smartctl_run) / 60 > 30
      for: 5m
      labels:
        severity: informational
    - alert: SmartTemp
      annotations:
        message: '"{{`{{ $labels.type }}`}}" "{{`{{ $labels.disk }}`}}" temperature: "{{`{{ printf "%.0f" $value }}`}}"C '
      expr: smartmon_airflow_temperature_cel_raw_value > 40 or smartmon_temperature_celsius_raw_value > 40
      for: 5m
      labels:
        severity: informational
    - alert: SmartTemp
      annotations:
        message: '"{{`{{ $labels.type }}`}}" "{{`{{ $labels.disk }}`}}" temperature: "{{`{{ printf "%.0f" $value }}`}}"C '
      expr: smartmon_airflow_temperature_cel_raw_value > 60 or smartmon_temperature_celsius_raw_value > 60
      for: 5m
      labels:
        severity: warning
    - alert: SmartE2E
      annotations:
        message: 'SMART "{{`{{ $labels.type }}`}}" "{{`{{ $labels.disk }}`}}" e2e fails'
      expr: smartmon_end_to_end_error_value <= smartmon_end_to_end_error_threshold 
      for: 5m
      labels:
        severity: informational
    - alert: SmartReallocated
      annotations:
        message: 'SMART "{{`{{ $labels.type }}`}}" "{{`{{ $labels.disk }}`}}" reallocated sectors '
      expr: smartmon_reallocated_sector_ct_value <= smartmon_reallocated_sector_ct_threshold
      for: 1m
      labels:
        severity: informational 
    - alert: SmartProgramFailCountTotal
      annotations:
        message: '"{{`{{ $labels.instance }}`}}" of job "{{`{{ $labels.job }}`}}" has less than 10% SMART Program Fail Count Total '
      expr: smartmon_program_fail_cnt_total_value < smartmon_program_fail_cnt_total_threshold
      for: 3m
      labels:
        severity: critical
    - alert: SmartECC
      annotations:
        message: 'SMART "{{`{{ $labels.type }}`}}" "{{`{{ $labels.disk }}`}}" ecc recovered "{{`{{ printf "%.0f" $value }}`}}"/day '
      expr: increase(smartmon_hardware_ecc_recovered_raw_value[1d]) > 0
      for: 1m
      labels:
        severity: informational
    - alert: SmartCRC
      annotations:
        message: 'SMART "{{`{{ $labels.type }}`}}" "{{`{{ $labels.disk }}`}}" cable crc errors '
      expr: smartmon_udma_crc_error_count_raw_value > 0
      for: 1m
      labels:
        severity: informational
    - alert: SmartPending
      annotations:
        message: 'SMART "{{`{{ $labels.type }}`}}" "{{`{{ $labels.disk }}`}}" pending sectors "{{`{{printf "%.0f" $value}}`}}" '
      expr: smartmon_current_pending_sector_raw_value > 1
      for: 1m
      labels:
        severity: informational
    - alert: SmartErase
      annotations:
        message: 'SMART "{{`{{ $labels.type }}`}}" "{{`{{ $labels.disk }}`}}" erase fail count "{{`{{printf "%.0f" $value}}`}}"/day '
      expr: increase(smartmon_erase_fail_count_total_raw_value[1d]) > 0
      for: 1m
      labels:
        severity: informational
    - alert: SMARTReallocatedSectors
      annotations:
        message: ' Disk has reallocated sectors '
      expr: smartmon_reallocated_sector_ct_raw_value > 0
      for: 1m
      labels:
        severity: warning
    - alert: SMARTMonitorNotRunning
      annotations:
        message: ' Periodic SMART monitoring not running (timer/service disabled?) '
      expr: time() - node_textfile_mtime_seconds{file="smartmon.prom"} > 3600
      for: 1h
      labels:
        severity: info
    - alert: SmartMonDeviceLifeLeftLow
      annotations:
        message: ' "{{`{{ $labels.instance }}`}}" of job "{{`{{ $labels.job }}`}}" is reporting that a physical hard disk has less than 50% expected life left '
      expr: smartmon_wear_leveling_count_value < smartmon_wear_leveling_count_threshold
      for: 3m
      labels:
        severity: critical

{{- end }}
