{
 "title": "Unbound",
 "description": "Unbound DNS resolver metrics",
 "tags": [
  "unbound",
  "dns",
  "resolver"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(unbound_up, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Queries",
   "type": "stat",
   "description": "Total number of queries received at the selected time range.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(unbound_queries_total{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Queries per second",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(unbound_queries_total{instance=\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "description": "The number of threads created to serve clients",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(unbound_queries_total{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Cache hit/miss ratio",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "format": "short",
   "valueName": "total",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(unbound_cache_hits_total{instance=\"$instance\"}[$__range]))",
     "legendFormat": "Hits"
    },
    {
     "expr": "sum(increase(unbound_cache_misses_total{instance=\"$instance\"}[$__range]))",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cache Hit Avg%",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(unbound_cache_hits_total{instance=\"$instance\"}[$__range]))/sum(increase(unbound_queries_total{instance=\"$instance\"}[$__range]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Prefetches",
   "type": "stat",
   "description": "Total number of cache prefetches performed",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(unbound_prefetches_total{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Cache Hit Now %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(unbound_cache_hits_total{instance=\"$instance\"}[5m]))/sum(increase(unbound_queries_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "now"
    }
   ]
  },
  {
   "title": "Recursive Replies %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(unbound_recursive_replies_total{instance=\"$instance\"}[$__range]))/sum(increase(unbound_queries_total{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Recursive Queries Median",
   "type": "stat",
   "description": "The median of the time it took to answer queries that needed recursive processing",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "unbound_recursion_time_seconds_median{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Recursive Queries Average",
   "type": "stat",
   "description": "Average time it took to answer queries that needed recursive processing (does not include in-cache requests).",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "unbound_recursion_time_seconds_avg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Request/Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(unbound_queries_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(unbound_cache_hits_total{instance=\"$instance\"}[5m]))/sum(increase(unbound_queries_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Recursion Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "unbound_recursion_time_seconds_median{instance=\"$instance\"}",
     "legendFormat": "median"
    },
    {
     "expr": "unbound_recursion_time_seconds_avg{instance=\"$instance\"}",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Recursive Replies Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(unbound_recursive_replies_total{instance=\"$instance\"}[5m]))/sum(increase(unbound_queries_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Prefetch Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(unbound_prefetches_total{instance=\"$instance\"}[5m]))/sum(increase(unbound_queries_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "prefetch"
    }
   ]
  },
  {
   "title": "Per thread",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total queries by thread",
   "type": "timeseries",
   "description": "Total number of queries handled by each worker thread",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(unbound_queries_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{thread}}"
    }
   ]
  },
  {
   "title": "Total cache prefetches by thread",
   "type": "timeseries",
   "description": "Total number of cache prefetches performed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(unbound_prefetches_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{thread}}"
    }
   ]
  },
  {
   "title": "Request list",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request list size",
   "type": "timeseries",
   "description": "Current size of the request list, including internally generated queries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(unbound_request_list_current_all{instance=\"$instance\"}[5m]))",
     "legendFormat": "all"
    },
    {
     "expr": "sum(rate(unbound_request_list_current_user{instance=\"$instance\"}[5m]))",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Total exceeded queries/sec",
   "type": "timeseries",
   "description": "Number of queries that were dropped because the request list was full",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(unbound_request_list_exceeded_total{instance=\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total overwritten queries",
   "type": "timeseries",
   "description": "Total number of requests in the request list that were overwritten by newer entries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(unbound_request_list_overwritten_total{instance=\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cache hits / misses",
   "type": "timeseries",
   "description": "Hits: total number of queries that were successfully answered using a cache lookup.\n\nMisses: total number of cache queries that needed recursive processing",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(unbound_cache_hits_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "hits"
    },
    {
     "expr": "sum(irate(unbound_cache_misses_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "misses"
    }
   ]
  }
 ]
}