#
# MIT License
#
# (C) Copyright 2022-2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: v2
name: cray-sysmgmt-health
version: 1.2.0
description: An extension of the official prometheus-operator helm chart for monitoring
keywords:
- sysmgmt-health
- victoriametrics
- grafana
- victoria-metrics-operator
- prometheus-node-exporter
- alertmanager
- smartmon
- monitoring
- alerting
home: https://github.com/Cray-HPE/cray-sysmgmt-health
sources:
- https://github.com/Cray-HPE/cray-sysmgmt-health
dependencies:
- name: victoria-metrics-k8s-stack
  repository: https://victoriametrics.github.io/helm-charts
  version: 0.24.5
- name: prometheus-snmp-exporter
  repository: https://prometheus-community.github.io/helm-charts
  version: 1.1.0
- name: logstash-exporter
  repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
  version: 1.0.2
- name: redfish-exporter
  repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
  version: 1.1.0

maintainers:
- name: rambabubolla
- name: shreniagrawal
appVersion: 0.24.5
annotations:
  artifacthub.io/images: |
    - name: alertmanager
      image: artifactory.algol60.net/csm-docker/stable/quay.io/prometheus/alertmanager:v0.25.0
    - name: configmap-reload
      image: artifactory.algol60.net/csm-docker/stable/docker.io/jimmidyson/configmap-reload:v0.3.0
    - name: prometheus
      image: artifactory.algol60.net/csm-docker/stable/quay.io/prometheus/prometheus:v2.41.0
    - name: prometheus-config-reloader
      image: artifactory.algol60.net/csm-docker/stable/docker.io/prom/prometheus-config-reloader:v0.62.0
  artifacthub.io/license: MIT
