{
 "title": "Kea-dhcp",
 "tags": [
  "Prometheus",
  "Kea-dhcp"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "host",
    "query": {
     "query": "label_values({__name__=~\"kea_dhcp.*\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ACK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kea_dhcp4_packets_sent_total{instance=~\"$host\", operation=\"ack\"}) by (instance)",
     "legendFormat": "{{instance}} (ipv4)"
    },
    {
     "expr": "sum(kea_dhcp6_packets_sent_total{instance=~\"$host\", operation=\"ack\"}) by (instance)",
     "legendFormat": "{{instance}} (ipv6)"
    },
    {}
   ]
  },
  {
   "title": "Offer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kea_dhcp4_packets_sent_total{instance=~\"$host\", operation=\"offer\"}) by (instance)",
     "legendFormat": "{{instance}} (ipv4)"
    },
    {
     "expr": "sum(kea_dhcp6_packets_sent_total{instance=~\"$host\", operation=\"offer\"}) by (instance)",
     "legendFormat": "{{instance}} (ipv6)"
    }
   ]
  },
  {
   "title": "Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kea_dhcp4_packets_received_total{instance=~\"$host\", operation=\"request\"}) by (instance)",
     "legendFormat": "{{instance}} (ipv4)"
    },
    {
     "expr": "sum(kea_dhcp6_packets_received_total{instance=~\"$host\", operation=\"request\"}) by (instance)",
     "legendFormat": "{{instance}} (ipv6)"
    }
   ]
  },
  {
   "title": "Discover",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kea_dhcp4_packets_received_total{instance=~\"$host\", operation=\"discover\"}) by (instance)",
     "legendFormat": "{{instance}} (ipv4)"
    },
    {
     "expr": "sum(kea_dhcp6_packets_received_total{instance=~\"$host\", operation=\"discover\"}) by (instance)",
     "legendFormat": "{{instance}} (ipv6)"
    }
   ]
  },
  {
   "title": "DHCP Leases in use",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kea_dhcp4_addresses_assigned_total{instance=~\"$host\"}/kea_dhcp4_addresses_total{instance=~\"$host\"}) by (subnet)",
     "legendFormat": "{{subnet}}"
    },
    {
     "expr": "sum(kea_dhcp6_na_assigned_total{instance=~\"$host\"}/kea_dhcp6_na_total{instance=~\"$host\"}) by (subnet)",
     "legendFormat": "{{subnet}}"
    }
   ]
  },
  {
   "title": "DHCP Leases History",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kea_dhcp4_addresses_assigned_total{instance=~\"$host\"}) by (subnet)",
     "legendFormat": "{{subnet}}"
    },
    {
     "expr": "sum(kea_dhcp6_na_assigned_total{instance=~\"$host\"}) by (subnet)",
     "legendFormat": "{{subnet}}"
    }
   ]
  },
  {
   "title": "Addresses declined",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kea_dhcp4_addresses_declined_total{instance=~\"$host\"}) by (instance)",
     "legendFormat": "{{instance}} (ipv4)"
    }
   ]
  },
  {
   "title": "Addresses declined reclaimed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kea_dhcp4_addresses_declined_reclaimed_total{instance=~\"$host\"}) by (instance)",
     "legendFormat": "{{instance}} (ipv4)"
    }
   ]
  },
  {
   "title": "Addresses reclaimed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kea_dhcp4_addresses_reclaimed_total{instance=~\"$host\"}) by (instance)",
     "legendFormat": "{{instance}} (ipv4)"
    }
   ]
  }
 ]
}