apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cray-metallb
  name: metallb-controller
  namespace: sysmgmt-health
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - metallb-system
  podMetricsEndpoints:
  - path: /metrics
    port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: cray-metallb
      app.kubernetes.io/name: metallb
