---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: patch-service-monitors
rules:
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [get, patch]
  - apiGroups: [""]
    resources: [pods]
    verbs: [list, get, delete]
  - apiGroups: ["monitoring.coreos.com"]
    resources: [servicemonitors, prometheusrules]
    verbs: [get, patch]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: patch-service-monitors
subjects:
  - kind: ServiceAccount
    name: patch-service-monitors
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: patch-service-monitors
  apiGroup: rbac.authorization.k8s.io
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: patch-service-monitors
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secure-metrics-scrape
rules:
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  verbs:
  - get
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-endpoint
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secure-metrics-scrape
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
