#
# MIT License
#
# (C) Copyright 2022-2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
{{- range $key, $val := .Values.servicemonitors }}
{{- if $val.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  {{- if $val.cluster }}
  name: {{ printf "%s-%s-%s-%s" (include "cray-sysmgmt-health.fullname" $)  $val.servicename $val.cluster "exporter"  | trunc 63 | trimSuffix "-"}}
  {{- else}}
  name: {{ printf "%s-%s--%s" (include "cray-sysmgmt-health.fullname" $)  $val.servicename  "exporter"  | trunc 63 | trimSuffix "-"}}
  {{- end }}
  namespace: {{ $val.serviceMonitor.namespace }}
  labels:
    {{- if $val.cluster }}
    app: {{ printf "%s-%s-%s-%s" (include "cray-sysmgmt-health.fullname" $)  $val.servicename $val.cluster "exporter"  | trunc 63 | trimSuffix "-"}}
    {{- else }}
    app: {{ printf "%s-%s--%s" (include "cray-sysmgmt-health.fullname" $)  $val.servicename  "exporter"  | trunc 63 | trimSuffix "-"}}
    {{- end }}
    release: {{ template "cray-sysmgmt-health.name" $ }}
{{ include "cray-sysmgmt-health.labels" $ | indent 4 }}
spec:
  selector:
    matchLabels:
{{ toYaml $val.serviceMonitor.matchLabels | indent 6 }}
  namespaceSelector:
    matchNames:
      {{- range $val.serviceMonitor.matchNamespace }}
      - {{ . }}
      {{- end }}
  endpoints:
  - port: {{ $val.serviceMonitor.port }}
    {{- if $val.serviceMonitor.interval }}
    interval: {{ $val.serviceMonitor.interval }}
    {{- end }}
    {{- if $val.serviceMonitor.honor_labels }}
    honorLabels: {{ $val.serviceMonitor.honor_labels }}
    {{- end }}
    {{- if eq $val.serviceMonitor.scheme "https" }}
    scheme: https
    tlsConfig:
      {{- if $val.serviceMonitor.serverName }}
      serverName: {{ $val.serviceMonitor.serverName }}
      {{- end }}
      {{- if $val.serviceMonitor.caFile }}
      caFile: {{ $val.serviceMonitor.caFile }}
      {{- end }}
      {{- if  $val.serviceMonitor.certFile }}
      certFile: {{ $val.serviceMonitor.certFile }}
      {{- end }}
      {{- if $val.serviceMonitor.keyFile }}
      keyFile: {{ $val.serviceMonitor.keyFile }}
      {{- end}}
      {{- if $val.serviceMonitor.ca }}
      ca:
        secret:
          key: {{ $val.serviceMonitor.ca.key }}
          name: {{ $val.serviceMonitor.ca.name }}
      {{- end }}
      {{- if  $val.serviceMonitor.cert }}
      cert:
        secret:
          key: {{ $val.serviceMonitor.cert.key }}
          name: {{ $val.serviceMonitor.cert.name }}
      {{- end }}
      {{- if $val.serviceMonitor.keySecret }}
      keySecret:
        key: {{ $val.serviceMonitor.keySecret.key }}
        name: {{ $val.serviceMonitor.keySecret.name }}
      {{- end}}
      {{- if $val.serviceMonitor.insecureSkipVerify }}
      insecureSkipVerify: {{ $val.serviceMonitor.insecureSkipVerify }}
      {{- end}}
    {{ else if eq $val.serviceMonitor.scheme "http" }}
    scheme: http
    {{- end }}
{{- if $val.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml $val.serviceMonitor.metricRelabelings | indent 4) . }}
{{- end }}
{{- if $val.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml $val.serviceMonitor.relabelings | indent 4 }}
{{- end }}
{{- end }}
---
{{- end }}
