#
# MIT License
#
# (C) Copyright 2021-2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
{{- if (index .Values "victoria-metrics-k8s-stack" "grafana" "enabled") }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "cray-sysmgmt-health.fullname" . }}-grafana
  labels:
    app: {{ template "cray-sysmgmt-health.name" . }}-grafana
{{ include "cray-sysmgmt-health.labels" . | indent 4 }}
spec:
  {{- with .Values.global.authGateways }}
  gateways:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  hosts:
  - {{ (index .Values "victoria-metrics-k8s-stack" "grafana" "externalAuthority") }}
  http:
  - match:
    - authority:
        exact: {{ (index .Values "victoria-metrics-k8s-stack" "grafana" "externalAuthority") }}
    route:
    - destination:
        host: {{ template "cray-sysmgmt-health.victoria-metrics-k8s-stack.grafana.fullname" . }}
        port:
          number: 80
      headers:
        request:
          add:
            # Sets the externally authenticated and authorized user to "admin"
            # such that all valid users have admin access to Grafana.
            X-WEBAUTH-USER: admin
          remove:
          # Remove "Authorization" header otherwise Grafana expects a valid
          # API key.
          - Authorization
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ template "cray-sysmgmt-health.fullname" . }}-grafana
  labels:
    app: {{ template "cray-sysmgmt-health.name" . }}-grafana
{{ include "cray-sysmgmt-health.labels" . | indent 4 }}
spec:
  host: {{ template "cray-sysmgmt-health.victoria-metrics-k8s-stack.grafana.fullname" . }}
  trafficPolicy:
    tls:
      mode: DISABLE
{{- end }}
