{
 "title": "FluentBit",
 "description": "This is a simple dashboard for Fluent-bit",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Active Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\"})"
    }
   ]
  },
  {
   "title": "Fluent-bit input bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(fluentbit_input_bytes_total[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Fluent-bit output bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(fluentbit_output_proc_bytes_total[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Fluent-bit error/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(fluentbit_output_errors_total[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Fluent-bit retries/fails",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(fluentbit_output_retries_total[1m])",
     "legendFormat": "Retries {{ pod }}"
    },
    {
     "expr": "rate(fluentbit_output_retries_failed_total[1m])",
     "legendFormat": "Failed {{ pod }}"
    }
   ]
  }
 ]
}