{
 "title": "Thanos / Overview",
 "description": "This dashboard provides a resource usage overview of the Thanos components Querier, Query-Frontend, Compacter and Store.\r\n\r\nIt includes CPU and Memory requests, limits and usage. In addition, the last termination reason is plotted and the cache hit ratio is available.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "![logo](https://repository-images.githubusercontent.com/109162639/97e49180-661b-11e9-9882-fdc44b74debd)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count\n(\n  kube_pod_container_info{container=~\"thanos.*\"}\n) by (container)\n",
     "legendFormat": "{{app_kubernetes_io_component}}"
    }
   ]
  },
  {
   "title": "Thanos / Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "DS_PROMETHEUS",
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Core Usage vs. Requested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_shares{container=\"thanos-query\"}) by (pod) / 1000",
     "legendFormat": "{{pod}} limit"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"thanos-query\"}[$__interval])) by (pod)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_spec_memory_limit_bytes{pod=~\"thanos-query.*\", pod!~\"thanos-query-frontend.*\"}) by (pod)",
     "legendFormat": "{{pod}} (limit)"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{container=\"thanos-query\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Thanos / Ruler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Core Usage vs. Requested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_shares{container=\"thanos-ruler\"}) by (pod) / 1000",
     "legendFormat": "{{pod}} limit"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"thanos-ruler\"}[$__interval])) by (pod)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_spec_memory_limit_bytes{pod=~\"thanos-ruler.*\"}) by (pod)",
     "legendFormat": "{{pod}} (limit)"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{container=~\"thanos-ruler.*\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Thanos / Compactor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Core Usage vs. Requested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_shares{container=\"thanos-compactor\"}) by (pod) / 1000",
     "legendFormat": "{{pod}} limit"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"thanos-compactor\"}[$__interval])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_spec_memory_limit_bytes{pod=~\"thanos-compactor.*\"}) by (pod)",
     "legendFormat": "{{pod}} (limit)"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{container=~\"thanos-compactor\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Thanos / Store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "repeat": "DS_PROMETHEUS",
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Core Usage vs. Requested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_shares{container=\"thanos-store\"}) by (pod) / 1000",
     "legendFormat": "{{pod}} limit"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"thanos-store\"}[$__interval])) by (pod)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_spec_memory_limit_bytes{pod=~\"thanos-store.*\"}) by (pod)",
     "legendFormat": "{{pod}} (limit)"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{container=~\"thanos-store\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}