{{- if .Values.cephNodeExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cray-sysmgmt-health.fullname" . }}-ceph-node-exporter
  labels:
    app: {{ template "cray-sysmgmt-health.name" . }}-ceph-node-exporter
    release: {{ template "cray-sysmgmt-health.name" . }}
    jobLabel: nodeExporter
{{ include "cray-sysmgmt-health.labels" . | indent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http-metrics
      protocol: TCP
      port: {{ .Values.cephNodeExporter.service.port }}
      targetPort: {{ .Values.cephNodeExporter.service.targetPort }}
{{- end }}
