{
 "title": "Prometheus Network Exporter SNMP",
 "description": "Prometheus Network Exporter",
 "tags": [
  "linux",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "switch",
    "query": {
     "query": "label_values(ifOperStatus, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Switch Stats (Port Tx/Rx)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Transmit / Receive",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{instance=\"$switch\"}[5m])"
    },
    {
     "expr": "irate(ifHCInOctets{instance=\"$switch\"}[5m])"
    },
    {
     "expr": "delta(ifHCOutOctets{instance=\"$switch\"}[$__range])"
    }
   ]
  },
  {
   "title": "Switch Stats (Packet types)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tx Broadcast Packets",
   "type": "timeseries",
   "description": "The total number of packets that higher-level protocols requested be transmitted, and which were addressed to a broadcast address at this sub-layer",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutBroadcastPkts{instance=\"$switch\"}[1h])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Tx Unicast Packets",
   "type": "timeseries",
   "description": "The total number of packets that higher-level protocols requested be transmitted, and which were not addressed to a multicast or broadcast address at this sub-layer",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutUcastPkts{instance=\"$switch\"}[$__range])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Rx Unicast Packets",
   "type": "timeseries",
   "description": "The number of packets, delivered by this sub-layer to a higher (sub-)layer, which were not addressed to a multicast or broadcast address at this sub-layer",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInUcastPkts{instance=\"$switch\"}[$__range])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Rx Broadcast Packets",
   "type": "timeseries",
   "description": "The number of packets, delivered by this sub-layer to a higher (sub-)layer, which were not addressed to a broadcast address at this sub-layer",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInBroadcastPkts{instance=\"$switch\"}[$__range])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Tx Multicast Packets",
   "type": "timeseries",
   "description": "The total number of packets that higher-level protocols requested be transmitted, and which were addressed to a multicast address at this sub-layer",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutMulticastPkts{instance=\"$switch\"}[$__range])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Tx Broadcast Packets",
   "type": "timeseries",
   "description": "The total number of packets that higher-level protocols requested be transmitted, and which were addressed to a broadcast address at this sub-layer",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutBroadcastPkts{instance=\"$switch\"}[$__range])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Rx Multicast Packets",
   "type": "timeseries",
   "description": "The number of packets, delivered by this sub-layer to a higher (sub-)layer, which were not addressed to a multicast address at this sub-layer",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{instance=\"$switch\"}[$__range])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Tx Unicast Packets",
   "type": "timeseries",
   "description": "The total number of packets that higher-level protocols requested be transmitted, and which were not addressed to a multicast or broadcast address at this sub-layer",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutUcastPkts{instance=\"$switch\"}[$__range])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Rx Broadcast Packets",
   "type": "timeseries",
   "description": "The number of packets, delivered by this sub-layer to a higher (sub-)layer, which were not addressed to a broadcast address at this sub-layer",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInBroadcastPkts{instance=\"$switch\"}[$__range])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Rx Unicast Packets",
   "type": "timeseries",
   "description": "The number of packets, delivered by this sub-layer to a higher (sub-)layer, which were not addressed to a multicast or broadcast address at this sub-layer",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInUcastPkts{instance=\"$switch\"}[$__range])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Tx Multicast Packets",
   "type": "timeseries",
   "description": "The total number of packets that higher-level protocols requested be transmitted, and which were addressed to a multicast address at this sub-layer",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutMulticastPkts{instance=\"$switch\"}[$__range])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Rx Multicast Packets",
   "type": "timeseries",
   "description": "The number of packets, delivered by this sub-layer to a higher (sub-)layer, which were not addressed to a multicast address at this sub-layer",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{instance=\"$switch\"}[$__range])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  }
 ]
}