#
# MIT License
#
# (C) Copyright 2021-2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "cray-sysmgmt-health.fullname" . }}-patch-nodeexporter-alerts-{{ .Release.Revision }}"
  labels:
{{ include "cray-sysmgmt-health.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-failed,before-hook-creation
spec:
  template:
    metadata:
      name: "{{ include "cray-sysmgmt-health.fullname" . }}-patch-nodeexporter-alerts-{{ .Release.Revision }}"
      labels:
{{ include "cray-sysmgmt-health.labels" . | indent 8 }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      serviceAccountName: "patch-nodeexporter-alerts"
      containers:
        - name: "patch-nodeexporter-alerts"
          image: "{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}"
          imagePullPolicy: {{ .Values.kubectl.image.pullPolicy }}
          command:
            - '/bin/sh'
          args:
            - '-c'
            - 'until kubectl get  -n sysmgmt-health   prometheusrules cray-sysmgmt-health-kube-p-node-exporter > /dev/null 2>&1; do echo "Waiting for cray-sysmgmt-health-kube-p-node-exporter alerts to be created"; sleep 5; done; /usr/local/sbin/fix-NodeClockSkewDetected-alert.sh; /usr/local/sbin/fix-CephNetworkPacketsDropped-alert.sh; /usr/local/sbin/fix-NodeFilesystemAlmostOutOfSpace-alert.sh; /usr/local/sbin/fix-Nodenumcpu-alert.sh'
          volumeMounts:
          - mountPath: /usr/local/sbin
            name: patch-nodeexporter-alerts
          securityContext:
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
      volumes:
      - name: patch-nodeexporter-alerts
        configMap:
          name: patch-nodeexporter-alerts
          defaultMode: 0755
