name: Lint, test, and scan Helm charts
on:
  pull_request:
    branches:
      - master
      - release/**
  workflow_dispatch:
jobs:
  lint-test-scan:
    uses: Cray-HPE/.github/.github/workflows/charts-lint-test-scan.yml@main
    with:
      scan-charts: false
      lint-charts: ${{ github.event_name == 'pull_request' }}
      ct-config: |
        chart-dirs:
          - kubernetes
        validate-maintainers: false
      scan-chart-snyk-args: "--severity-threshold=high --policy-path=kubernetes/.snyk"
      scan-images: false
      scan-image-snyk-args: "--severity-threshold=high --policy-path=kubernetes/.snyk"
      test-charts: false
    secrets:
      snyk-token: ${{ secrets.SNYK_TOKEN }}
